name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

# using fork here, because it contains a backported fix. Can be dropped after bump to v4.20.0
[[require]]
name = "doc-gen4"
git = "https://github.com/mo271/doc-gen4"
rev = "b760b91540bcf92c2ab6ac2bc28207e090769da8"

[[lean_exe]]
name = "overwrite_index"
srcDir = "scripts"
root = "overwrite_index"
exeName = "overwrite_index"
supportInterpreter = true
