/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import Mathlib.Analysis.InnerProductSpace.l2Space
public import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The rapidly decreasing Calkin algebra

This file gives an elementary model for the operator algebra occurring in Clausen's analytic
algebraic K-theory of the complex numbers. We work on the separable Hilbert space
$H = \ell^2(\mathbb{N}, \mathbb{C})$.

For a bounded operator `T`, its `n`th approximation error is the infimum of `‖T - S‖` over
operators `S` which factor through an `n`-dimensional Hilbert space. On a Hilbert space these are
the approximation numbers, and for compact operators they agree with the singular values (up to
the choice of indexing). Thus `IsRapidlyDecaying T` says exactly that the singular values of `T`
decay faster than every inverse power of `n`.

The generalized Calkin algebra is the quotient of all bounded operators by the two-sided ideal
generated by the rapidly decaying ones. Analytically, the rapidly decaying operators are already
a two-sided ideal.

## Main declarations

- `RapidDecayOperator.approximationError`: distance to operators of rank at most `n`.
- `RapidDecayOperator.IsRapidlyDecaying`: rapid decay of the approximation errors.
- `RapidDecayOperator.calkinAlgebra`: bounded operators modulo rapidly decaying operators.
-/

@[expose] public section

open Filter
open scoped lp Topology

noncomputable section

namespace RapidDecayOperator

/-- The standard separable infinite-dimensional complex Hilbert space. -/
abbrev HilbertSpace := ℓ²(ℕ, ℂ)

/-- The ring of bounded operators on the standard separable complex Hilbert space. -/
abbrev BoundedOperator := HilbertSpace →L[ℂ] HilbertSpace

/-- The infimal operator-norm error in approximating `T` by an operator which factors through an
`n`-dimensional complex Hilbert space. -/
noncomputable def approximationError (T : BoundedOperator) (n : ℕ) : ℝ :=
  sInf (Set.range fun p :
      (HilbertSpace →L[ℂ] EuclideanSpace ℂ (Fin n)) ×
        (EuclideanSpace ℂ (Fin n) →L[ℂ] HilbertSpace) ↦
    ‖T - p.2.comp p.1‖)

/-- Approximation errors are nonnegative. -/
theorem approximationError_nonneg (T : BoundedOperator) (n : ℕ) :
    0 ≤ approximationError T n := by
  apply le_csInf (Set.range_nonempty _)
  rintro _ ⟨p, rfl⟩
  exact norm_nonneg _

/-- The zero finite-rank approximation bounds the approximation error by the operator norm. -/
theorem approximationError_le_norm (T : BoundedOperator) (n : ℕ) :
    approximationError T n ≤ ‖T‖ := by
  apply csInf_le
  · exact ⟨0, by rintro _ ⟨p, rfl⟩; exact norm_nonneg _⟩
  · exact ⟨⟨0, 0⟩, by simp⟩

@[simp] theorem approximationError_zero (n : ℕ) : approximationError 0 n = 0 := by
  exact le_antisymm (by simpa using approximationError_le_norm 0 n)
    (approximationError_nonneg 0 n)

/-- At rank zero, the only possible approximant is zero. -/
@[simp] theorem approximationError_rank_zero (T : BoundedOperator) :
    approximationError T 0 = ‖T‖ := by
  apply le_antisymm (approximationError_le_norm T 0)
  apply le_csInf (Set.range_nonempty _)
  rintro _ ⟨⟨p, q⟩, rfl⟩
  have hp : p = 0 := Subsingleton.elim _ _
  simp [hp]

/-- An operator factoring through the prescribed finite-dimensional space has zero approximation
error at that rank. -/
@[simp] theorem approximationError_comp (n : ℕ)
    (p : HilbertSpace →L[ℂ] EuclideanSpace ℂ (Fin n))
    (q : EuclideanSpace ℂ (Fin n) →L[ℂ] HilbertSpace) :
    approximationError (q.comp p) n = 0 := by
  apply le_antisymm _ (approximationError_nonneg _ _)
  apply csInf_le
  · exact ⟨0, by rintro _ ⟨r, rfl⟩; exact norm_nonneg _⟩
  · exact ⟨⟨p, q⟩, by simp⟩

/-- The infimum defining `approximationError` can be approached arbitrarily closely. -/
theorem exists_approximation_lt (T : BoundedOperator) (n : ℕ) {ε : ℝ} (hε : 0 < ε) :
    ∃ (p : HilbertSpace →L[ℂ] EuclideanSpace ℂ (Fin n))
      (q : EuclideanSpace ℂ (Fin n) →L[ℂ] HilbertSpace),
      ‖T - q.comp p‖ < approximationError T n + ε := by
  have hlt : approximationError T n < approximationError T n + ε := lt_add_of_pos_right _ hε
  obtain ⟨_, ⟨⟨p, q⟩, rfl⟩, hpq⟩ :=
    exists_lt_of_csInf_lt (Set.range_nonempty _) hlt
  exact ⟨p, q, hpq⟩

/-- Postcomposition multiplies approximation errors by at most the operator norm. -/
theorem approximationError_comp_left (S T : BoundedOperator) (n : ℕ) :
    approximationError (S.comp T) n ≤ ‖S‖ * approximationError T n := by
  apply le_of_forall_pos_le_add
  intro ε hε
  have hden : 0 < ‖S‖ + 1 := by positivity
  obtain ⟨p, q, hpq⟩ := exists_approximation_lt T n (div_pos hε hden)
  calc
    approximationError (S.comp T) n ≤ ‖S.comp T - (S.comp q).comp p‖ := by
      apply csInf_le
      · exact ⟨0, by rintro _ ⟨r, rfl⟩; exact norm_nonneg _⟩
      · exact ⟨⟨p, S.comp q⟩, rfl⟩
    _ = ‖S.comp (T - q.comp p)‖ := by
      congr 1
      ext x
      simp
    _ ≤ ‖S‖ * ‖T - q.comp p‖ := ContinuousLinearMap.opNorm_comp_le _ _
    _ ≤ ‖S‖ * approximationError T n + ε := by
      have hS : 0 ≤ ‖S‖ := norm_nonneg _
      rcases hS.eq_or_lt with hS0 | hSpos
      · rw [← hS0]
        simp only [zero_mul, zero_add]
        exact hε.le
      have hmul := mul_lt_mul_of_pos_left hpq hSpos
      have hfrac : ‖S‖ * (ε / (‖S‖ + 1)) < ε := by
        rw [mul_div]
        exact (div_lt_iff₀ hden).2 (by nlinarith)
      nlinarith

/-- Precomposition multiplies approximation errors by at most the operator norm. -/
theorem approximationError_comp_right (T S : BoundedOperator) (n : ℕ) :
    approximationError (T.comp S) n ≤ approximationError T n * ‖S‖ := by
  apply le_of_forall_pos_le_add
  intro ε hε
  have hden : 0 < ‖S‖ + 1 := by positivity
  obtain ⟨p, q, hpq⟩ := exists_approximation_lt T n (div_pos hε hden)
  calc
    approximationError (T.comp S) n ≤ ‖T.comp S - q.comp (p.comp S)‖ := by
      apply csInf_le
      · exact ⟨0, by rintro _ ⟨r, rfl⟩; exact norm_nonneg _⟩
      · exact ⟨⟨p.comp S, q⟩, rfl⟩
    _ = ‖(T - q.comp p).comp S‖ := by
      congr 1
    _ ≤ ‖T - q.comp p‖ * ‖S‖ := ContinuousLinearMap.opNorm_comp_le _ _
    _ ≤ approximationError T n * ‖S‖ + ε := by
      have hS : 0 ≤ ‖S‖ := norm_nonneg _
      rcases hS.eq_or_lt with hS0 | hSpos
      · rw [← hS0]
        simp only [mul_zero, zero_add]
        exact hε.le
      have hmul := mul_lt_mul_of_pos_right hpq hSpos
      have hfrac : (ε / (‖S‖ + 1)) * ‖S‖ < ε := by
        rw [div_mul_eq_mul_div]
        exact (div_lt_iff₀ hden).2 (by nlinarith)
      nlinarith

/-- A bounded operator is rapidly decaying when its approximation errors decay faster than every
inverse power. For compact operators on a Hilbert space, the approximation errors are the singular
values. -/
def IsRapidlyDecaying (T : BoundedOperator) : Prop :=
  ∀ k : ℕ, Tendsto (fun n : ℕ ↦ ((n + 1 : ℕ) : ℝ) ^ k * approximationError T n)
    atTop (𝓝 0)

@[simp] theorem isRapidlyDecaying_zero : IsRapidlyDecaying 0 := by
  intro k
  simp

/-- Rapid decay in particular gives approximation in operator norm. -/
theorem IsRapidlyDecaying.tendsto_approximationError {T : BoundedOperator}
    (hT : IsRapidlyDecaying T) : Tendsto (approximationError T) atTop (𝓝 0) := by
  simpa using hT 0

/-- Rapid decay is preserved by postcomposition with an arbitrary bounded operator. -/
theorem IsRapidlyDecaying.comp_left {T : BoundedOperator} (hT : IsRapidlyDecaying T)
    (S : BoundedOperator) : IsRapidlyDecaying (S.comp T) := by
  intro k
  apply squeeze_zero
  · intro n
    exact mul_nonneg (by positivity) (approximationError_nonneg _ _)
  · intro n
    exact mul_le_mul_of_nonneg_left (approximationError_comp_left S T n) (by positivity)
  · simpa [mul_assoc, mul_left_comm] using (hT k).const_mul ‖S‖

/-- Rapid decay is preserved by precomposition with an arbitrary bounded operator. -/
theorem IsRapidlyDecaying.comp_right {T : BoundedOperator} (hT : IsRapidlyDecaying T)
    (S : BoundedOperator) : IsRapidlyDecaying (T.comp S) := by
  intro k
  apply squeeze_zero
  · intro n
    exact mul_nonneg (by positivity) (approximationError_nonneg _ _)
  · intro n
    exact mul_le_mul_of_nonneg_left (approximationError_comp_right T S n) (by positivity)
  · simpa [mul_assoc] using (hT k).mul_const ‖S‖

/-- Rapid decay is preserved by scalar multiplication. -/
theorem IsRapidlyDecaying.smul {T : BoundedOperator} (hT : IsRapidlyDecaying T) (z : ℂ) :
    IsRapidlyDecaying (z • T) := by
  convert hT.comp_left (z • ContinuousLinearMap.id ℂ HilbertSpace) using 1
  ext x
  simp

/-- The projection onto the zeroth coordinate of `ℓ²(ℕ, ℂ)`. -/
noncomputable def rankOneProjection : BoundedOperator :=
  (lp.singleContinuousLinearMap ℂ (fun _ : ℕ ↦ ℂ) 2 0).comp
    (lp.evalCLM ℂ (fun _ : ℕ ↦ ℂ) 2 0)

@[simp] theorem rankOneProjection_apply (x : HilbertSpace) :
    rankOneProjection x = lp.single 2 0 (x 0) := rfl

@[simp] theorem rankOneProjection_apply_zero (x : HilbertSpace) :
    rankOneProjection x 0 = x 0 := by
  simp

/-- The rank-one coordinate projection is rapidly decaying. -/
theorem rankOneProjection_isRapidlyDecaying : IsRapidlyDecaying rankOneProjection := by
  intro k
  refine (tendsto_congr' ?_).2 tendsto_const_nhds
  filter_upwards [eventually_ge_atTop 1] with n hn
  obtain ⟨i, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (by omega : n ≠ 0)
  let p : HilbertSpace →L[ℂ] EuclideanSpace ℂ (Fin (i + 1)) :=
    (EuclideanSpace.equiv (Fin (i + 1)) ℂ).symm.toContinuousLinearMap.comp
      (ContinuousLinearMap.pi fun j : Fin (i + 1) ↦
        if j = 0 then lp.evalCLM ℂ (fun _ : ℕ ↦ ℂ) 2 0 else 0)
  let q : EuclideanSpace ℂ (Fin (i + 1)) →L[ℂ] HilbertSpace :=
    (lp.singleContinuousLinearMap ℂ (fun _ : ℕ ↦ ℂ) 2 0).comp
      ((ContinuousLinearMap.proj 0).comp
        (EuclideanSpace.equiv (Fin (i + 1)) ℂ).toContinuousLinearMap)
  have hpq : q.comp p = rankOneProjection := by
    ext x j
    simp [p, q, rankOneProjection]
  have herr : approximationError rankOneProjection (i + 1) = 0 := by
    rw [← hpq]
    exact approximationError_comp (i + 1) p q
  rw [herr]
  simp

/-- The rank-one coordinate projection is idempotent. -/
theorem rankOneProjection_idempotent :
    rankOneProjection.comp rankOneProjection = rankOneProjection := by
  ext x i
  by_cases hi : i = 0
  · subst i
    change (lp.single (E := fun _ : ℕ ↦ ℂ) 2 0 (x 0)) 0 = x 0
    simp
  · simp [rankOneProjection, hi]

/-- The rank-one coordinate projection is nonzero. -/
theorem rankOneProjection_ne_zero : rankOneProjection ≠ 0 := by
  intro h
  have hx := congrArg (fun T : BoundedOperator ↦ T (lp.single 2 0 (1 : ℂ)) 0) h
  change rankOneProjection (lp.single 2 0 (1 : ℂ)) 0 = 0 at hx
  rw [rankOneProjection_apply_zero] at hx
  simp at hx

/-- The two-sided ideal generated by the rapidly decaying bounded operators. -/
noncomputable def ideal : TwoSidedIdeal BoundedOperator :=
  TwoSidedIdeal.span {T | IsRapidlyDecaying T}

/-- Scalar multiples of the rank-one coordinate projection, as elements of the rapid-decay
ideal. This is the concrete rank-one corner used in the Hochschild comparison. -/
noncomputable def rankOne : ℂ →ₗ[ℂ] ideal where
  toFun z := ⟨z • rankOneProjection, by
    apply TwoSidedIdeal.subset_span
    exact rankOneProjection_isRapidlyDecaying.smul z⟩
  map_add' x y := by
    apply Subtype.ext
    exact add_smul x y rankOneProjection
  map_smul' x y := by
    apply Subtype.ext
    simp [mul_smul]

@[simp] theorem rankOne_coe (z : ℂ) : (rankOne z : BoundedOperator) = z • rankOneProjection := rfl

/-- The rank-one corner is injective. -/
theorem rankOne_injective : Function.Injective rankOne := by
  intro x y hxy
  have hc : (rankOne x : BoundedOperator) = rankOne y := congrArg Subtype.val hxy
  rw [rankOne_coe, rankOne_coe] at hc
  have hv := congrArg (fun T : BoundedOperator ↦ T (lp.single 2 0 (1 : ℂ))) hc
  have h := congrArg (fun v : HilbertSpace ↦ v 0) hv
  change x * (rankOneProjection (lp.single 2 0 (1 : ℂ)) 0) =
    y * (rankOneProjection (lp.single 2 0 (1 : ℂ)) 0) at h
  rw [rankOneProjection_apply_zero] at h
  change x * 1 = y * 1 at h
  simpa using h

/-- The generalized Calkin algebra of bounded operators modulo rapidly decaying operators. -/
noncomputable abbrev calkinAlgebra := ideal.ringCon.Quotient

end RapidDecayOperator
