/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil
import FormalConjectures.Wikipedia.LeopoldtConjecture

/-!
# The elementary form and the `p`-adic-relation form agree

`Leopoldt.LeopoldtConjecture` says that on the subgroup generated by a fundamental system the
topology induced by the congruences modulo $p^M \mathcal{O}_K$ is the $p$-adic topology;
`Leopoldt.leopoldt_conjecture` says that the map
$\varphi_\varepsilon : \mathbb{Z}_p^r \to U_1$ is injective. This file proves them equivalent
(`leopoldtConjecture_iff`).

Both directions run through the fundamental system: a family of maximal rank differs from
`fundSystem K` by an invertible integer matrix, and $\mathbb{Z}^r$ is dense in $\mathbb{Z}_p^r$.
-/

open Filter IsDedekindDomain NumberField NumberField.Units

open scoped NumberField

namespace Leopoldt

section directions

variable {K : Type*} [Field K] [NumberField K] {p : ℕ} [Fact p.Prime]

/-- The elementary form of Leopoldt's conjecture implies the statement of `leopoldt_conjecture`
for every family of units of maximal rank (the hypothesis `IsPrincipalUnitAbove` is not needed
for this direction). -/
@[category API, AMS 11]
theorem LeopoldtConjecture.eq_zero_of_isPadicRelation (h : LeopoldtConjecture K p)
    {ε : Fin (rank K) → (𝓞 K)ˣ} (hmax : IsMaxRank ε) {a : Fin (rank K) → ℤ_[p]}
    (ha : IsPadicRelation K p ε a) : a = 0 := by
  classical
  have hw : torsionOrder K ≠ 0 := torsionOrder_ne_zero K
  choose ζe hζe using fun i ↦ (exist_unique_eq_mul_prod K (ε i)).exists
  set C : Matrix (Fin (rank K)) (Fin (rank K)) ℤ := fun i j ↦ (ζe i).2 j * torsionOrder K
  have hC : ∀ i, ε i ^ torsionOrder K = ∏ j, fundSystem K j ^ C i j := by
    intro i
    have hζ : ((ζe i).1 : (𝓞 K)ˣ) ^ torsionOrder K = 1 :=
      (mem_rootsOfUnity _ _).1 (by rw [rootsOfUnity_eq_torsion]; exact (ζe i).1.2)
    rw [hζe i, mul_pow, hζ, one_mul, ← Finset.prod_pow]
    refine Finset.prod_congr rfl fun j _ ↦ ?_
    rw [← zpow_natCast, ← zpow_mul]
  have hdet : C.det ≠ 0 := det_ne_zero_of_isMaxRank (isMaxRank_pow hmax hw) C hC
  have hz : ∀ n, ∏ i, (ε i ^ torsionOrder K) ^ (a i).appr n =
      ∏ j, fundSystem K j ^ Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j :=
    fun n ↦ prod_pow_eq_prod_fundSystem _ C hC _
  have hconv : ∀ M : ℕ, ∀ᶠ n in atTop, (p : 𝓞 K) ^ M ∣
      ((∏ j, fundSystem K j ^ Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j : (𝓞 K)ˣ) : 𝓞 K)
        - 1 := by
    intro M
    refine eventually_dvd_of_tendsto (f := fun n ↦
      ((∏ j, fundSystem K j ^ Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j : (𝓞 K)ˣ) : 𝓞 K))
      (fun v hv ↦ ?_) M
    have := (ha v hv).pow (torsionOrder K)
    rw [one_pow] at this
    refine this.congr fun n ↦ ?_
    have e1 : (∏ i, ε i ^ (a i).appr n) ^ torsionOrder K =
        ∏ i, (ε i ^ torsionOrder K) ^ (a i).appr n := by
      rw [← Finset.prod_pow]
      exact Finset.prod_congr rfl fun i _ ↦ by rw [← pow_mul, ← pow_mul, mul_comm]
    rw [← hz n, coe_prod_pow, coe_coe_adicCompletion, coe_coe_adicCompletion, ← map_pow,
      ← Units.val_pow_eq_pow_val, e1]
  have hN : ∀ N : ℕ, ∀ j, Matrix.vecMul a ((Int.castRingHom ℤ_[p]).mapMatrix C) j ∈
      Ideal.span {(p : ℤ_[p]) ^ N} := by
    intro N j
    obtain ⟨M, hM⟩ := h N
    obtain ⟨n, hn⟩ := ((hconv M).and (eventually_ge_atTop N)).exists
    have hdvd : (p : ℤ) ^ N ∣ Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j := hM _ hn.1 j
    have h1 : ((Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j : ℤ) : ℤ_[p]) ∈
        Ideal.span {(p : ℤ_[p]) ^ N} := by
      rw [Ideal.mem_span_singleton]
      have := Int.cast_dvd_cast (α := ℤ_[p]) _ _ hdvd
      push_cast at this
      exact this
    have h2 : Matrix.vecMul a ((Int.castRingHom ℤ_[p]).mapMatrix C) j -
        ((Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j : ℤ) : ℤ_[p]) ∈
        Ideal.span {(p : ℤ_[p]) ^ N} := by
      have : Matrix.vecMul a ((Int.castRingHom ℤ_[p]).mapMatrix C) j -
          ((Matrix.vecMul (fun i ↦ ((a i).appr n : ℤ)) C j : ℤ) : ℤ_[p]) =
          ∑ i, (a i - ((a i).appr n : ℤ_[p])) * (C i j : ℤ_[p]) := by
        simp [Matrix.vecMul, dotProduct, Finset.sum_sub_distrib, sub_mul,
          RingHom.mapMatrix_apply, Matrix.map_apply]
      rw [this]
      exact Ideal.sum_mem _ fun i _ ↦ Ideal.mul_mem_right _ _
        (Ideal.span_singleton_le_span_singleton.2 (pow_dvd_pow _ hn.2) (PadicInt.appr_spec n (a i)))
    simpa using add_mem h2 h1
  have hzero : Matrix.vecMul a ((Int.castRingHom ℤ_[p]).mapMatrix C) = 0 :=
    funext fun j ↦ eq_zero_of_forall_mem_span_pow fun N ↦ hN N j
  have hdet' : ((Int.castRingHom ℤ_[p]).mapMatrix C).det ≠ 0 := by
    rw [← RingHom.map_det, eq_intCast, Int.cast_ne_zero]
    exact hdet
  have := congrArg (fun x ↦ Matrix.vecMul x ((Int.castRingHom ℤ_[p]).mapMatrix C).adjugate) hzero
  simp only [Matrix.vecMul_vecMul, Matrix.mul_adjugate, Matrix.vecMul_smul, Matrix.vecMul_one,
    Matrix.zero_vecMul] at this
  exact (smul_eq_zero.1 this).resolve_left hdet'

/-- The statement of `leopoldt_conjecture` for every admissible family of units implies the
elementary form of Leopoldt's conjecture. -/
@[category API, AMS 11]
theorem leopoldtConjecture_of_forall_isPadicRelation
    (h : ∀ ε : Fin (rank K) → (𝓞 K)ˣ, IsMaxRank ε → (∀ i, IsPrincipalUnitAbove K p (ε i)) →
      ∀ a : Fin (rank K) → ℤ_[p], IsPadicRelation K p ε a → a = 0) :
    LeopoldtConjecture K p := by
  classical
  obtain ⟨Q, hQ0, hQ⟩ := exists_pow_sub_one_dvd (K := K) (p := p)
  set ε : Fin (rank K) → (𝓞 K)ˣ := fun i ↦ fundSystem K i ^ Q
  have hε' : ∀ i, ε i = fundSystem K i ^ Q := fun i ↦ rfl
  have hmax : IsMaxRank ε := isMaxRank_pow (isMaxRank_fundSystem K) hQ0
  have hone : ∀ i, IsPrincipalUnitAbove K p (ε i) := fun i v hv ↦ Ideal.mem_of_dvd _ (hQ _) hv
  have hpow : ∀ i (n : ℕ), (p : 𝓞 K) ^ (n + 1) ∣ ((ε i ^ p ^ n : (𝓞 K)ˣ) : 𝓞 K) - 1 :=
    fun i n ↦ pow_pow_sub_one_dvd (hQ _) n
  intro N
  by_contra hN
  simp only [not_exists, not_forall] at hN
  choose e he hbad using hN
  choose ι hι using hbad
  obtain ⟨⟨a, i₀⟩, -, φ, hφ, hlim⟩ := IsCompact.tendsto_subseq
    (x := fun M ↦ ((fun i ↦ ((e M i : ℤ) : ℤ_[p])), ι M)) isCompact_univ fun _ ↦ Set.mem_univ _
  obtain ⟨hlim1, hlim2⟩ := (Prod.tendsto_iff _ _).1 hlim
  dsimp only [Function.comp_def] at hlim1 hlim2
  rw [nhds_discrete, tendsto_pure] at hlim2
  rw [tendsto_pi_nhds] at hlim1
  have hne : a i₀ ≠ 0 := by
    intro h0
    have hp1 : (0 : ℝ) < (p : ℝ) ^ (-(N : ℤ)) :=
      zpow_pos (by exact_mod_cast (Fact.out : p.Prime).pos) _
    obtain ⟨k₁, hk₁⟩ := Metric.tendsto_atTop.1 (hlim1 i₀) _ hp1
    obtain ⟨k₂, hk₂⟩ := eventually_atTop.1 hlim2
    have h1 := hk₁ (max k₁ k₂) (le_max_left _ _)
    have h2 := hk₂ (max k₁ k₂) (le_max_right _ _)
    rw [h0, dist_zero_right] at h1
    exact hι (φ (max k₁ k₂)) (by rw [h2]; exact PadicInt.norm_int_le_pow_iff_dvd.1 h1.le)
  have hrel : IsPadicRelation K p ε a := by
    intro v hv
    have := tendsto_of_forall_eventually_dvd (K := K) hv
      (f := fun n ↦ ((∏ i, ε i ^ (a i).appr n : (𝓞 K)ˣ) : 𝓞 K)) ?_
    · refine this.congr fun n ↦ ?_
      rw [coe_prod_pow]
    intro M
    rw [eventually_atTop]
    refine ⟨M, fun n hn ↦ ?_⟩
    have hp1 : (0 : ℝ) < (p : ℝ) ^ (-(n : ℤ)) :=
      zpow_pos (by exact_mod_cast (Fact.out : p.Prime).pos) _
    choose k₁ hk₁ using fun i ↦ Metric.tendsto_atTop.1 (hlim1 i) _ hp1
    set k := max (Finset.univ.sup k₁) M
    have hφk : M ≤ φ k := le_trans (le_max_right _ _) (hφ.id_le k)
    have hk : ∀ i, ((p ^ n : ℕ) : ℤ) ∣ ((a i).appr n : ℤ) - e (φ k) i := by
      intro i
      have h1 := hk₁ i k (le_trans (Finset.le_sup (Finset.mem_univ i)) (le_max_left _ _))
      rw [dist_eq_norm] at h1
      have h2 : ((e (φ k) i : ℤ) : ℤ_[p]) - a i ∈ Ideal.span {(p : ℤ_[p]) ^ n} :=
        (PadicInt.norm_le_pow_iff_mem_span_pow _ n).1 h1.le
      have h3 := PadicInt.appr_spec n (a i)
      have h4 : ((((a i).appr n : ℤ) - e (φ k) i : ℤ) : ℤ_[p]) ∈ Ideal.span {(p : ℤ_[p]) ^ n} := by
        have := neg_mem (add_mem h2 h3)
        convert this using 1
        push_cast
        ring
      exact_mod_cast PadicInt.norm_int_le_pow_iff_dvd.1
        ((PadicInt.norm_le_pow_iff_mem_span_pow _ n).2 h4)
    have hred : ∀ i, redUnits ((p : 𝓞 K) ^ M) (ε i) ^ (p ^ n) = 1 := by
      intro i
      rw [← map_pow, redUnits_eq_one_iff]
      exact (pow_dvd_pow _ (by omega : M ≤ n + 1)).trans (hpow i n)
    rw [← redUnits_eq_one_iff, map_prod]
    calc ∏ i, redUnits ((p : 𝓞 K) ^ M) (ε i ^ (a i).appr n)
        = ∏ i, redUnits ((p : 𝓞 K) ^ M) (fundSystem K i) ^ ((Q : ℤ) * e (φ k) i) := by
          refine Finset.prod_congr rfl fun i _ ↦ ?_
          rw [map_pow, ← zpow_natCast, zpow_eq_zpow_of_pow_eq_one (hred i) (hk i), hε' i, map_pow,
            ← zpow_natCast, ← zpow_mul]
      _ = redUnits ((p : 𝓞 K) ^ M) (∏ i, fundSystem K i ^ e (φ k) i) ^ (Q : ℤ) := by
          rw [map_prod, ← Finset.prod_zpow]
          refine Finset.prod_congr rfl fun i _ ↦ ?_
          rw [map_zpow, ← zpow_mul, mul_comm]
      _ = 1 := by
          rw [(redUnits_eq_one_iff _ _).2 ((pow_dvd_pow _ hφk).trans (he (φ k))), one_zpow]
  exact hne (congrFun (h ε hmax hone a hrel) i₀)

end directions

variable (K : Type*) [Field K] [NumberField K] (p : ℕ) [Fact p.Prime]

/--
The two formulations agree. `LeopoldtConjecture K p` is the statement that on the subgroup
generated by a fundamental system the topology induced by the congruences modulo
$p^M \mathcal{O}_K$ is the $p$-adic topology; `leopoldt_conjecture` is the statement that
$\varphi_\varepsilon : \mathbb{Z}_p^r \to U_1$ is injective.

They are equivalent because $\mathbb{Z}^r$ is dense in the compact group $\mathbb{Z}_p^r$ and
$\varphi_\varepsilon$ is continuous, so injectivity of $\varphi_\varepsilon$ is the same as the
two topologies on $\mathbb{Z}^r$ agreeing. The congruences modulo $p^M \mathcal{O}_K$ are
cofinal among the neighbourhoods of $1$ in $U_1$, since
$\mathcal{O}_K / p^M \mathcal{O}_K \cong \prod_{\mathfrak{p} \mid p}
\mathcal{O}_\mathfrak{p} / p^M \mathcal{O}_\mathfrak{p}$. Replacing `fundSystem K` by another
family `ε` of maximal rank changes the generated subgroup by a finite index only, which changes
neither side.
-/
@[category API, AMS 11]
theorem leopoldtConjecture_iff :
    LeopoldtConjecture K p ↔
      ∀ ε : Fin (rank K) → (𝓞 K)ˣ, IsMaxRank ε → (∀ i, IsPrincipalUnitAbove K p (ε i)) →
        ∀ a : Fin (rank K) → ℤ_[p], IsPadicRelation K p ε a → a = 0 :=
  ⟨fun h _ hmax _ _ ha ↦ h.eq_zero_of_isPadicRelation hmax ha,
    leopoldtConjecture_of_forall_isPadicRelation⟩

/-
## The `p`-adic regulator form

The `p`-adic logarithms of the fundamental units at all embeddings `σ : K → ℂ_p` form an
`r × n` matrix, `n = [K : ℚ]`. Leopoldt's conjecture in its original form says that this matrix
has full rank `r`, i.e. that a `p`-adic regulator (an `r × r` minor) does not vanish.
-/

end Leopoldt
