/-
Copyright 2026 The Formal Conjectures Authors.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Demazure's Conjecture on Representations of Algebraic Groups

*References:*
- [Demazure1974] M. Demazure,
  [Désingularisation des variétés de Schubert généralisées](https://doi.org/10.24033/asens.1261),
  Ann. Sci. École Norm. Sup. **7** (1974), 53–88.
- [LMS1979] V. Lakshmibai, C. Musili, C. S. Seshadri,
  [Geometry of G/P](https://doi.org/10.1090/S0273-0979-1979-14631-7),
  Bull. Amer. Math. Soc. (N.S.) **1** (1979), 432–435.
- [Li1998] P. Littelmann,
  [Contracting modules and standard monomial theory for symmetrizable Kac-Moody algebras](
  https://doi.org/10.1090/S0894-0347-98-00268-9),
  J. Amer. Math. Soc. **11** (1998), 551–567.
- [Wikipedia: Demazure conjecture](https://en.wikipedia.org/wiki/Demazure_conjecture)
- [Wikipedia: Demazure module](https://en.wikipedia.org/wiki/Demazure_module)
- [arXiv:1605.04953](https://arxiv.org/abs/1605.04953)

The **Demazure conjecture** concerns the character theory of finite-dimensional representations of reductive algebraic groups. For a reductive algebraic group $G$ over a field $k$ with Borel subgroup $B$, Weyl group $W$, weight lattice $\Lambda$, and Weyl vector $\rho$ (half-sum of positive roots), define the **Demazure module** $V_w(\lambda)$ for $w \in W$ and dominant weight $\lambda \in \Lambda^+$ as the $B$-submodule of the irreducible representation $V(\lambda)$ generated by the extremal weight space $V(\lambda)_{w \cdot \lambda}$.

Demazure conjectured (1974) that the formal character of $V_w(\lambda)$ in $\mathbb{Z}[\Lambda]$ is $$\operatorname{ch}(V_w(\lambda)) = \sum_{w' \leq w} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho},$$ where the sum is over the Bruhat lower set of $w$, $\ell$ is the Coxeter length function, and $\rho$ is the Weyl vector. Proved for classical groups by Lakshmibai–Musili–Seshadri (1979) via standard monomial theory, and for all reductive groups by Littelmann (1998) using path models.

Since the full theory of Demazure modules and their character rings is not yet formalized in Mathlib, we axiomatize the relevant objects and state the character identity with `sorry`.
-/

namespace DemazureConjecture

open Finset BigOperators

/--
The Demazure character formula for $V_w(\lambda)$, stated as an alternating sum over the
Bruhat lower set of $w$:
$$\operatorname{ch}(V_w(\lambda)) =
  \sum_{\substack{w' \in W \\ w' \leq w}} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho}.$$

The parameters are:
- `Λ`: the weight lattice (an additive abelian group),
- `W`: the Weyl group (finite, with Bruhat partial order),
- `ℓ : W → ℕ`: the Coxeter length function,
- `ρ : Λ`: the Weyl vector,
- `e : Λ →+ R`: the formal exponential map into the character ring `R`.
-/
noncomputable def demazureCharFormula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (w : W) (lam : Λ)
    (S : Finset W) (hS : ∀ w' : W, w' ∈ S ↔ w' ≤ w) : R :=
  ∑ w' ∈ S, (-1 : ℤ) ^ (ℓ w - ℓ w') • e (w' • (lam + ρ) - ρ)

/--
`IsDominant lam` asserts that `lam` is a dominant weight.
Since reductive algebraic groups are not yet fully in Mathlib, this is axiomatized with `sorry`.
-/
def IsDominant {Λ : Type*} [AddCommGroup Λ] (lam : Λ) : Prop := sorry

/--
`IsDemazureCharacter char` asserts that the function `char : W → Λ → R`
maps `(w, lam)` to the formal character of the Demazure module $V_w(\lambda)$.
Since Demazure modules are not in Mathlib, this is axiomatized with `sorry`.
-/
def IsDemazureCharacter
    {W Λ R : Type*} [Group W] [AddCommGroup Λ] [CommRing R] [SMul W Λ]
    (char : W → Λ → R) : Prop := sorry

/--
**The Demazure Conjecture** (Demazure 1974; proved by Lakshmibai–Musili–Seshadri 1979 and
Littelmann 1998).

For a reductive algebraic group $G$ with Weyl group $W$, weight lattice $\Lambda$, Weyl vector
$\rho$, and formal character ring $R = \mathbb{Z}[\Lambda]$, the formal character of the Demazure
$B$-module $V_w(\lambda)$ equals the alternating sum
$$\operatorname{ch}(V_w(\lambda)) =
  \sum_{w' \leq w} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho}$$
for every $w \in W$ and every dominant weight $\lambda \in \Lambda^+$.

Here `demazureChar w lam` denotes the formal character of the Demazure module $V_w(\lambda)$,
constrained by the `IsDemazureCharacter` predicate.
-/
@[category research solved, AMS 20 14 17]
theorem demazure_conjecture
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (bruhatBelow : W → Finset W)
    (hBruhat : ∀ (w : W) (w' : W), w' ∈ bruhatBelow w ↔ w' ≤ w)
    (demazureChar : W → Λ → R)
    (hChar : IsDemazureCharacter demazureChar) :
    ∀ (w : W) (lam : Λ), IsDominant lam →
      demazureChar w lam =
        demazureCharFormula ℓ ρ e w lam (bruhatBelow w) (hBruhat w) := by
  sorry

/--
**Sanity check: The identity element case**

When $w = 1$ (the identity element of $W$), the Demazure module $V_1(\lambda)$ is the one-dimensional Borel module with character $e^\lambda$. The Demazure formula reduces to: $$\operatorname{ch}(V_1(\lambda)) = (-1)^0 \cdot e^{1 \cdot (\lambda + \rho) - \rho} = e^\lambda.$$

This confirms that the Demazure formula specializes correctly to the minimal case.
-/
@[category test, AMS 20 17]
theorem demazure_conjecture.variants.identity_character
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (h_one_smul : ∀ μ : Λ, (1 : W) • μ = μ)
    (ℓ : W → ℕ) (hℓ_one : ℓ 1 = 0)
    (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (lam : Λ)
    (hS : ∀ w' : W, w' ∈ ({1} : Finset W) ↔ w' ≤ (1 : W)) :
    demazureCharFormula ℓ ρ e (1 : W) lam {1} hS = e lam := by
  simp only [demazureCharFormula, Finset.sum_singleton, hℓ_one, Nat.sub_self, pow_zero]
  rw [h_one_smul (lam + ρ), add_sub_cancel_right]
  simp

/--
**Variant: Monotonicity of Demazure modules**

If $w_1 \leq w_2$ in the Bruhat order, then $V_{w_1}(\lambda) \subseteq V_{w_2}(\lambda)$. At the level of the Bruhat lower sets, $w_1 \leq w_2$ implies $\{w' \mid w' \leq w_1\} \subseteq \{w' \mid w' \leq w_2\}$.
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.monotone_bruhat_below
    {W : Type*} [Preorder W]
    (bruhatBelow : W → Finset W)
    (hBruhat : ∀ (w : W) (w' : W), w' ∈ bruhatBelow w ↔ w' ≤ w) :
    ∀ (w₁ w₂ : W), w₁ ≤ w₂ → bruhatBelow w₁ ⊆ bruhatBelow w₂ := by
  intro w₁ w₂ h12 w' hw'
  rw [hBruhat w₂]
  exact le_trans ((hBruhat w₁ w').mp hw') h12

/--
**Variant: The Demazure formula for the longest element gives the Weyl character formula**

When $w = w_0$ (the longest element, the Bruhat maximum of $W$), the lower set equals all of $W$, and the Demazure character formula becomes the classical Weyl character formula: $$\operatorname{ch}(V(\lambda)) = \sum_{w' \in W} (-1)^{\ell(w_0) - \ell(w')} e^{w'(\lambda + \rho) - \rho}.$$
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.longest_element_is_weyl_formula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [LinearOrder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (lam : Λ)
    (w₀ : W) (hw₀ : ∀ w : W, w ≤ w₀) :
    demazureCharFormula ℓ ρ e w₀ lam Finset.univ
      (fun w' => Iff.intro (fun _ => hw₀ w') (fun _ => Finset.mem_univ _)) =
      ∑ w' : W, (-1 : ℤ) ^ (ℓ w₀ - ℓ w') • e (w' • (lam + ρ) - ρ) := by
  simp [demazureCharFormula]

end DemazureConjecture
