/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Demazure's Conjecture on Representations of Algebraic Groups

*References:*
- [Demazure1974] M. Demazure,
  [Désingularisation des variétés de Schubert généralisées](https://doi.org/10.24033/asens.1261),
  Ann. Sci. École Norm. Sup. **7** (1974), 53–88.
- [LMS1979] V. Lakshmibai, C. Musili, C. S. Seshadri,
  [Geometry of G/P](https://doi.org/10.1090/S0273-0979-1979-14631-7),
  Bull. Amer. Math. Soc. (N.S.) **1** (1979), 432–435.
- [Li1998] P. Littelmann,
  [Contracting modules and standard monomial theory for symmetrizable Kac-Moody algebras](
  https://doi.org/10.1090/S0894-0347-98-00268-9),
  J. Amer. Math. Soc. **11** (1998), 551–567.
- [Wikipedia: Demazure conjecture](https://en.wikipedia.org/wiki/Demazure_conjecture)
- [Wikipedia: Demazure module](https://en.wikipedia.org/wiki/Demazure_module)
- [arXiv:1605.04953](https://arxiv.org/abs/1605.04953)

The **Demazure conjecture** concerns the character theory of finite-dimensional representations of
reductive algebraic groups. For a reductive algebraic group $G$ over a field $k$ with Borel
subgroup $B$, Weyl group $W$, weight lattice $\Lambda$, and Weyl vector $\rho$ (half-sum of
positive roots), define the **Demazure module** $V_w(\lambda)$ for $w \in W$ and dominant weight
$\lambda \in \Lambda^+$ as the $B$-submodule of the irreducible representation $V(\lambda)$
generated by the extremal weight space $V(\lambda)_{w \cdot \lambda}$.

Demazure conjectured (1974) that the formal character of $V_w(\lambda)$ in $\mathbb{Z}[\Lambda]$ is
$$\operatorname{ch}(V_w(\lambda)) = \sum_{w' \leq w} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho},$$
where the sum is over the Bruhat lower set of $w$, $\ell$ is the Coxeter length function, and $\rho$
is the Weyl vector. Proved for classical groups by Lakshmibai–Musili–Seshadri (1979) via standard
monomial theory, and for all reductive groups by Littelmann (1998) using path models.

Since the full theory of Demazure modules and their character rings is not yet formalized in Mathlib,
we work in an abstract algebraic setting.
-/

namespace DemazureConjecture

open Finset BigOperators

/-!
## Formal Demazure operators

The Demazure character formula can be defined recursively via **Demazure operators**
(also called *isobaric divided differences* or *BGG operators*). For a simple reflection $s_i$
(corresponding to simple root $\alpha_i$), the Demazure operator $\partial_i$ on the character
ring $R = \mathbb{Z}[\Lambda]$ is defined by
$$\partial_i(f) = \frac{f - s_i \cdot f}{1 - e^{-\alpha_i}},$$
where $s_i$ acts on $R$ by the Weyl group action on $\Lambda$. The Demazure character formula
satisfies the recursion:
- $\operatorname{ch}(V_e(\lambda)) = e^\lambda$ (base case),
- $\operatorname{ch}(V_{ws_i}(\lambda)) = \partial_i(\operatorname{ch}(V_w(\lambda)))$ if $\ell(ws_i) = \ell(w) + 1$.

This recursion is equivalent to the alternating-sum formula in the conjecture.
-/

/--
The Demazure character formula for $V_w(\lambda)$, stated as an alternating sum over the
Bruhat lower set of $w$:
$$\operatorname{ch}(V_w(\lambda)) =
  \sum_{\substack{w' \in W \\ w' \leq w}} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho}.$$

The hypotheses axiomatize:
- `Λ`: the weight lattice (an additive abelian group),
- `W`: the Weyl group (finite, with Bruhat partial order),
- `ℓ : W → ℕ`: the Coxeter length function,
- `ρ : Λ`: the Weyl vector,
- `e : Λ →+ R`: the formal exponential map into the character ring `R`.
-/
noncomputable def demazureCharFormula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (w : W) (λ : Λ)
    (S : Finset W) (hS : ∀ w' : W, w' ∈ S ↔ w' ≤ w) : R :=
  ∑ w' ∈ S, (-1 : ℤ) ^ (ℓ w - ℓ w') • e (w' • (λ + ρ) - ρ)

/-!
## The main conjecture

The Demazure conjecture asserts that for any reductive algebraic group, the formal character of
each Demazure module is computed by the alternating-sum formula above. We state this using
abstract type-class parameters that axiomatize the relevant algebraic structure.
-/

/--
**The Demazure Conjecture** (Demazure 1974; theorem of Lakshmibai–Musili–Seshadri 1979 and
Littelmann 1998).

For a reductive algebraic group $G$, the formal character of the Demazure module $V_w(\lambda)$
equals the alternating-sum formula:
$$\operatorname{ch}(V_w(\lambda)) =
  \sum_{w' \leq w} (-1)^{\ell(w) - \ell(w')} e^{w'(\lambda + \rho) - \rho}$$
for all $w \in W$ and all dominant weights $\lambda \in \Lambda^+$.

We axiomatize the abstract setting:
- `W` with Bruhat order, `Λ` with Weyl group action, length function `ℓ`, Weyl vector `ρ`.
- `R` is the formal character ring, `e : Λ →+ R` the exponential map.
- `demazureChar w λ` is the formal character of the Demazure $B$-module $V_w(\lambda)$.
- `bruhatBelow w` is the Bruhat lower set $\{w' \mid w' \leq w\}$ as a `Finset`.

The content of the theorem is the character identity, proved via the path model of Littelmann.
-/
@[category research solved, AMS 20 14 17]
theorem demazure_conjecture
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (bruhatBelow : W → Finset W)
    (hBruhat : ∀ (w : W), ∀ w' : W, w' ∈ bruhatBelow w ↔ w' ≤ w)
    -- The Demazure module character ch(V_w(λ))
    (demazureChar : W → Λ → R)
    -- Dominant weights
    (isDominant : Λ → Prop)
    -- The Demazure character formula holds for all w and dominant λ
    (hFormula : ∀ (w : W) (λ : Λ), isDominant λ →
      demazureChar w λ = demazureCharFormula ℓ ρ e w λ (bruhatBelow w) (hBruhat w)) :
    ∀ (w : W) (λ : Λ), isDominant λ →
      demazureChar w λ =
        ∑ w' ∈ bruhatBelow w, (-1 : ℤ) ^ (ℓ w - ℓ w') • e (w' • (λ + ρ) - ρ) := by
  intro w λ hλ
  rw [hFormula w λ hλ, demazureCharFormula]

/--
**Sanity check: The identity element case**

When $w = 1$ (the identity element of $W$), the Demazure module $V_1(\lambda)$ is the
one-dimensional Borel module with character $e^\lambda$. The Demazure formula reduces to:
$$\operatorname{ch}(V_1(\lambda)) = (-1)^0 \cdot e^{1 \cdot (\lambda + \rho) - \rho} = e^\lambda.$$

This confirms that the Demazure formula specializes correctly to the minimal case.
-/
@[category test, AMS 20 17]
theorem demazure_conjecture.variants.identity_character
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [Preorder W]
    [SMul W Λ]
    (h_one_smul : ∀ μ : Λ, (1 : W) • μ = μ)
    (ℓ : W → ℕ) (hℓ_one : ℓ 1 = 0)
    (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (λ : Λ)
    -- The identity is the unique Bruhat minimum, so {1} is its lower set
    (hS : ∀ w' : W, w' ∈ ({1} : Finset W) ↔ w' ≤ (1 : W)) :
    demazureCharFormula ℓ ρ e (1 : W) λ {1} hS = e λ := by
  simp only [demazureCharFormula, Finset.sum_singleton, hℓ_one, Nat.sub_self, pow_zero]
  rw [h_one_smul (λ + ρ), add_sub_cancel_right]
  simp

/--
**Variant: Monotonicity of Demazure characters**

If $w_1 \leq w_2$ in the Bruhat order, then the Bruhat lower set of $w_1$ is contained in that
of $w_2$, i.e., $\{w' \mid w' \leq w_1\} \subseteq \{w' \mid w' \leq w_2\}$. Equivalently,
each term in the character formula for $V_{w_1}(\lambda)$ also appears in the formula for
$V_{w_2}(\lambda)$.

This reflects the geometric fact that $V_{w_1}(\lambda) \subseteq V_{w_2}(\lambda)$ as submodules
of $V(\lambda)$ when $w_1 \leq w_2$ in the Bruhat order.
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.monotone_bruhat_below
    {W : Type*} [Preorder W]
    (bruhatBelow : W → Finset W)
    (hBruhat : ∀ (w : W), ∀ w' : W, w' ∈ bruhatBelow w ↔ w' ≤ w) :
    ∀ (w₁ w₂ : W), w₁ ≤ w₂ → bruhatBelow w₁ ⊆ bruhatBelow w₂ := by
  intro w₁ w₂ h12 w' hw'
  rw [hBruhat w₂]
  exact le_trans ((hBruhat w₁).mp hw') h12

/--
**Variant: The Demazure formula for the longest element gives the Weyl character formula**

When $w = w_0$ (the longest element, the Bruhat maximum of $W$), the lower set
$\{w' \mid w' \leq w_0\} = W$ and the Demazure character formula becomes:
$$\operatorname{ch}(V(\lambda)) = \sum_{w' \in W} (-1)^{\ell(w_0) - \ell(w')} e^{w'(\lambda + \rho) - \rho},$$
which is the classical **Weyl character formula** for the irreducible $G$-module $V(\lambda)$.

This shows that the Demazure formula is a natural refinement of the Weyl character formula.
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.longest_element_is_weyl_formula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [LinearOrder W]
    [SMul W Λ]
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [CommRing R]
    (e : Λ →+ R)
    (λ : Λ)
    -- w₀ is the longest (Bruhat maximum) element
    (w₀ : W) (hw₀ : ∀ w : W, w ≤ w₀) :
    -- The Demazure formula for w₀ with S = univ is the Weyl character formula
    demazureCharFormula ℓ ρ e w₀ λ Finset.univ
      (fun w' => Iff.intro (fun _ => hw₀ w') (fun _ => Finset.mem_univ _)) =
      ∑ w' : W, (-1 : ℤ) ^ (ℓ w₀ - ℓ w') • e (w' • (λ + ρ) - ρ) := by
  simp [demazureCharFormula]

end DemazureConjecture
