/-
Copyright 2026 The Formal Conjectures Authors.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
-/

import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.Hom.Defs
import Mathlib.Algebra.Ring.Hom.Defs
import Mathlib.Data.Finset.Card
import FormalConjecturesUtil

/-!
# Demazure's Conjecture on Representations of Algebraic Groups

*References:*
- [Demazure1974] M. Demazure,
  [Désingularisation des variétés de Schubert généralisées](https://doi.org/10.24033/asens.1261),
  Ann. Sci. École Norm. Sup. **7** (1974), 53–88.
- [LMS1979] V. Lakshmibai, C. Musili, C. S. Seshadri,
  [Geometry of G/P](https://doi.org/10.1090/S0273-0979-1979-14631-7),
  Bull. Amer. Math. Soc. (N.S.) **1** (1979), 432–435.
- [Li1998] P. Littelmann,
  [Contracting modules and standard monomial theory for symmetrizable Kac-Moody algebras](
  https://doi.org/10.1090/S0894-0347-98-00268-9),
  J. Amer. Math. Soc. **11** (1998), 551–567.
- [Wikipedia: Demazure conjecture](https://en.wikipedia.org/wiki/Demazure_conjecture)
- [Wikipedia: Demazure module](https://en.wikipedia.org/wiki/Demazure_module)
- [arXiv:1605.04953](https://arxiv.org/abs/1605.04953)

The **Demazure conjecture** concerns the character theory of finite-dimensional
representations of reductive algebraic groups. For a reductive algebraic group $G$ over a
field $k$ with Borel subgroup $B$, Weyl group $W$, weight lattice $\Lambda$, and Weyl vector
$\rho$ (half-sum of positive roots), define the **Demazure module** $V_w(\lambda)$ for
$w \in W$ and dominant weight $\lambda \in \Lambda^+$ as the $B$-submodule of the
irreducible representation $V(\lambda)$ generated by the extremal weight space
$V(\lambda)_{w \cdot \lambda}$.

Demazure conjectured (1974) that, for a reduced word $w = s_{i_1} \cdots s_{i_\ell}$ in the
Coxeter generators, the formal character of $V_w(\lambda)$ in $\mathbb{Z}[\Lambda]$ is given
by the divided-difference (Demazure operator) formula
$$\operatorname{ch}(V_w(\lambda)) = \partial_w(e^{\lambda})
  := \partial_{i_1} \cdots \partial_{i_\ell}(e^{\lambda}), \qquad
  \partial_i f = \frac{f - e^{-\alpha_i}\, s_i f}{1 - e^{-\alpha_i}}.$$
Proved for classical groups by Lakshmibai–Musili–Seshadri (1979) via standard monomial
theory, and for all reductive groups by Littelmann (1998) using path models.

Since the full theory of Demazure modules and their character rings is not yet formalized
in Mathlib, we axiomatize the relevant objects and state the character identity with
`sorry`.
-/

namespace DemazureConjecture

open Finset BigOperators

/--
`demazureChar w lam` denotes the formal character of the Demazure `B`-module
$V_w(\lambda)$, as an element of the (unspecified) character ring `R`. Since Demazure
modules and their character rings are not yet formalized in Mathlib, this is axiomatized
rather than defined by `sorry`; see the module docstring for why an `axiom` is used instead
of `def ... := sorry` (a `sorry`-valued definition would not actually depend on `w`/`lam`).
-/
axiom demazureChar {W Λ R : Type*} : W → Λ → R

/--
`IsDominant lam` asserts that `lam` is a dominant weight. Axiomatized for the same reason as
`demazureChar` above: a `def ... := sorry` would not depend on `lam`.
-/
axiom IsDominant {Λ : Type*} : Λ → Prop

/--
The single Demazure divided-difference operator
$$\partial_s f = \frac{f - e^{-\alpha}\, (s \cdot f)}{1 - e^{-\alpha}},$$
where `s : W` acts on the character ring `R` via `wAct s`, `alpha : Λ` is the simple root
attached to `s`, and `e : Multiplicative Λ →* R` is the formal exponential.
-/
noncomputable def demazureOp
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*}
    {R : Type*} [Field R]
    (e : Multiplicative Λ →* R) (wAct : W → R →+* R)
    (s : W) (alpha : Λ) (f : R) : R :=
  (f - e (Multiplicative.ofAdd (-alpha)) * wAct s f) / (1 - e (Multiplicative.ofAdd (-alpha)))

/--
The Demazure character formula for $V_w(\lambda)$:
$$\operatorname{ch}(V_w(\lambda)) = \partial_{i_1} \cdots \partial_{i_\ell}(e^\lambda)$$
for a reduced word $w = s_{i_1} \cdots s_{i_\ell}$ in the Coxeter generators `S`, applying the
divided-difference operators `demazureOp` in order via a right fold (so the *first* letter of
`ws` is applied outermost, matching $\partial_w = \partial_{i_1} \circ \cdots \circ \partial_{i_\ell}$).

The parameters are:
- `Λ`: the weight lattice (an additive abelian group),
- `W`: the Weyl group,
- `S`: the Coxeter generating set (simple reflections),
- `simple : S → W`: the inclusion of generators into `W`,
- `simpleRoot : S → Λ`: the simple root attached to each generator,
- `e : Multiplicative Λ →* R`: the formal exponential map into the character field `R`,
- `wAct : W → R →+* R`: the action of `W` on the character ring `R`,
- `ws : List S`: a word in the generators (intended to be reduced for `w`).
-/
noncomputable def demazureCharFormula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W]
    {S : Type*}
    (simple : S → W) (simpleRoot : S → Λ)
    {R : Type*} [Field R]
    (e : Multiplicative Λ →* R) (wAct : W → R →+* R)
    (ws : List S) (lam : Λ) : R :=
  ws.foldr (fun s acc => demazureOp e wAct (simple s) (simpleRoot s) acc)
    (e (Multiplicative.ofAdd lam))

/--
**The Demazure Conjecture** (Demazure 1974; proved by Lakshmibai–Musili-Seshadri 1979 and Littelmann 1998).

For a reductive algebraic group $G$ with Weyl group $W$, Coxeter generating set `S`, weight lattice $\Lambda$, and formal character field $R$, the formal character of the Demazure $B$, module $V_w(\lambda)$ equals $\partial_w(e^\lambda)$ for every dominant weight $\lambda$, where `ws` is any reduced word for `w` (i.e. `ws.length = ℓ w`).

`wAct` is required to be an honest (right) action of `W` on `R` by ring automorphisms, compatible with `e` via `hAct`. `demazureChar w lam` denotes the formal character of the Demazure module $V_w(\lambda)$; see the module docstring for why it is axiomatized rather than passed in as a hypothesis-constrained variable.
-/
@[category research solved, AMS 20 14 17]
theorem demazure_conjecture
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [SMul W Λ]
    {S : Type*} (simple : S → W) (simpleRoot : S → Λ)
    (ℓ : W → ℕ)
    {R : Type*} [Field R]
    (e : Multiplicative Λ →* R) (wAct : W → R →+* R)
    (hAct1 : wAct 1 = RingHom.id R)
    (hActMul : ∀ w₁ w₂ : W, wAct (w₁ * w₂) = (wAct w₁).comp (wAct w₂))
    (hAct : ∀ (w : W) (μ : Λ), wAct w (e (Multiplicative.ofAdd μ)) =
      e (Multiplicative.ofAdd (w • μ)))
    (hgen : ∀ s : S, e (Multiplicative.ofAdd (-(simpleRoot s))) ≠ 1)
    (w : W) (ws : List S)
    (hword : (ws.map simple).prod = w) (hlen : ws.length = ℓ w)
    (lam : Λ) (hlam : IsDominant lam) :
    (demazureChar w lam : R) = demazureCharFormula simple simpleRoot e wAct ws lam := by
  sorry

/--
**Sanity check: The identity element case**

When `ws = []` (the empty word, a reduced word for `w = 1`), no divided-difference operators are applied, so $\partial_1(e^\lambda) = e^\lambda$. This matches the fact that the Demazure module $V_1(\lambda)$ is the one-dimensional Borel module with character $e^\lambda$. Unlike
the previous version's Weyl-numerator formula, this is now a genuine unfolding of the definition rather than a nontrivial identity.
-/
@[category test, AMS 20 17]
theorem demazure_conjecture.variants.identity_character
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W]
    {S : Type*} (simple : S → W) (simpleRoot : S → Λ)
    {R : Type*} [Field R]
    (e : Multiplicative Λ →* R) (wAct : W → R →+* R)
    (lam : Λ) :
    demazureCharFormula simple simpleRoot e wAct ([] : List S) lam =
      e (Multiplicative.ofAdd lam) := by
  simp [demazureCharFormula]

/--
**Variant: Monotonicity of Demazure modules**

If $w_1 \leq w_2$ in the Bruhat order, then $V_{w_1}(\lambda) \subseteq V_{w_2}(\lambda)$. At the level of the Bruhat lower sets, $w_1 \leq w_2$ implies $\{w' \mid w' \leq w_1\} \subseteq \{w' \mid w' \leq w_2\}$. (This structural fact about the Bruhat order is independent of the character-formula correction above, and was not flagged as
incorrect in review; `[Preorder W]` is tightened to `[PartialOrder W]` since the Bruhat order is genuinely a partial order.)
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.monotone_bruhat_below
    {W : Type*} [PartialOrder W]
    (bruhatBelow : W → Finset W)
    (hBruhat : ∀ (w : W) (w' : W), w' ∈ bruhatBelow w ↔ w' ≤ w) :
    ∀ (w₁ w₂ : W), w₁ ≤ w₂ → bruhatBelow w₁ ⊆ bruhatBelow w₂ := by
  intro w₁ w₂ h12 w' hw'
  rw [hBruhat w₂]
  exact le_trans ((hBruhat w₁ w').mp hw') h12

/--
**Variant: The Demazure formula for the longest element gives the classical Weyl character formula** (Weyl 1925).

When `w₀` is the longest element of `W`, a reduced word `ws₀` for `w₀` has length equal to the number `posRoots.card` of positive roots, and the Demazure operator formula specializes to the classical Weyl character formula
$$\partial_{w_0}(e^\lambda) =
  \frac{\sum_{w \in W} (-1)^{\ell(w)} e^{w(\lambda+\rho)-\rho}}{\prod_{\alpha > 0} (1 - e^{-\alpha})}.$$
Unlike the identity-element sanity check above, this is a real classical theorem (essentially the content of Weyl's character formula), **not** a restatement of the definition, so it is recorded here as its own `sorry` rather than proved by `simp`.
-/
@[category research solved, AMS 20 17]
theorem demazure_conjecture.variants.longest_element_is_weyl_formula
    {Λ : Type*} [AddCommGroup Λ]
    {W : Type*} [Group W] [Fintype W] [SMul W Λ]
    {S : Type*} (simple : S → W) (simpleRoot : S → Λ)
    (ℓ : W → ℕ) (ρ : Λ)
    {R : Type*} [Field R]
    (e : Multiplicative Λ →* R) (wAct : W → R →+* R)
    (hAct : ∀ (w : W) (μ : Λ), wAct w (e (Multiplicative.ofAdd μ)) =
      e (Multiplicative.ofAdd (w • μ)))
    (posRoots : Finset Λ)
    (w₀ : W) (ws₀ : List S)
    (hword : (ws₀.map simple).prod = w₀) (hlen : ws₀.length = posRoots.card)
    (lam : Λ) :
    demazureCharFormula simple simpleRoot e wAct ws₀ lam =
      (∑ w : W, (-1 : ℤ) ^ ℓ w • e (Multiplicative.ofAdd (w • (lam + ρ) - ρ))) /
        (∏ α ∈ posRoots, (1 - e (Multiplicative.ofAdd (-α)))) := by
  sorry

end DemazureConjecture
