/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import Mathlib.Algebra.Regular.Basic
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial

/-!
# Blowups and finite sequences of blowups

`IdealSheafData.IsEffectiveCartier` says that an ideal is locally generated by a
nonzerodivisor. `IdealSheafData.IsBlowup` characterizes a morphism by the universal
property of the blowup: it is terminal among morphisms for which the inverse-image
ideal is effective Cartier. The definition uses the image ideal `I.comap f`.

`BlowupSequence` records a finite composition, with a prescribed condition on each
center over a fixed base. These definitions do not choose a construction of blowups.

*References:*
* [Stacks, effective Cartier divisors](https://stacks.math.columbia.edu/tag/01WQ).
* [Stacks, universal property of blowing up](https://stacks.math.columbia.edu/tag/0806).
-/

@[expose] public section

open CategoryTheory

universe u

namespace AlgebraicGeometry.Scheme

namespace IdealSheafData

variable {X Y Z : Scheme.{u}}

/-- An ideal defining an effective Cartier divisor: locally it is generated by a
nonzerodivisor. The empty divisor, generated by `1`, is allowed. -/
def IsEffectiveCartier (I : X.IdealSheafData) : Prop :=
  ∀ x : X, ∃ U : X.affineOpens, x ∈ U.1 ∧
    ∃ a : Γ(X, U), IsRegular a ∧ I.ideal U = Ideal.span {a}

/-- The empty closed subscheme is an effective Cartier divisor. -/
theorem isEffectiveCartier_top : (⊤ : X.IdealSheafData).IsEffectiveCartier := by
  intro x
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, _⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
  exact ⟨⟨U, hU⟩, hxU, 1, isRegular_one, by simp⟩

/-- The whole of a nonempty scheme is not an effective Cartier divisor. -/
theorem not_isEffectiveCartier_bot [Nonempty X] :
    ¬ (⊥ : X.IdealSheafData).IsEffectiveCartier := by
  intro h
  obtain ⟨x⟩ := ‹Nonempty X›
  obtain ⟨U, hxU, a, ha, hgen⟩ := h x
  have : Nonempty U.1 := ⟨⟨x, hxU⟩⟩
  have ha0 : a = 0 := Ideal.span_singleton_eq_bot.mp (by simpa using hgen.symm)
  exact zero_ne_one (ha.left (a₁ := 0) (a₂ := 1) (by simp [ha0]))

/-- A morphism is the blowup in `I` if its inverse-image ideal is effective Cartier
and every morphism with that property factors through it uniquely over `X`. -/
structure IsBlowup (I : X.IdealSheafData) (π : Y ⟶ X) : Prop where
  /-- The scheme-theoretic inverse image of the center is an effective Cartier divisor. -/
  isEffectiveCartier : (I.comap π).IsEffectiveCartier
  /-- The universal property, tested against all schemes in the same universe. -/
  universal : ∀ (T : Scheme.{u}) (f : T ⟶ X), (I.comap f).IsEffectiveCartier →
    ∃! g : T ⟶ Y, g ≫ π = f

/-- Blowing up an effective Cartier divisor gives the identity. -/
theorem IsEffectiveCartier.isBlowup_id {I : X.IdealSheafData}
    (hI : I.IsEffectiveCartier) : I.IsBlowup (𝟙 X) where
  isEffectiveCartier := by simpa using hI
  universal T f _ := ⟨f, by simp, fun g hg => by simpa using hg⟩

/-- Blowing up the empty center gives the identity. -/
theorem isBlowup_top_id : (⊤ : X.IdealSheafData).IsBlowup (𝟙 X) :=
  isEffectiveCartier_top.isBlowup_id

/-- Two morphisms into a blowup agree if their composites agree and the source
has effective Cartier inverse-image ideal. -/
theorem IsBlowup.hom_ext {I : X.IdealSheafData} {π : Y ⟶ X} (hπ : I.IsBlowup π)
    {f : Z ⟶ X} (hf : (I.comap f).IsEffectiveCartier) {g h : Z ⟶ Y}
    (hg : g ≫ π = f) (hh : h ≫ π = f) : g = h :=
  (hπ.universal Z f hf).unique hg hh

/-- Blowups in the same ideal are isomorphic over the base. -/
theorem IsBlowup.exists_iso {I : X.IdealSheafData} {π : Y ⟶ X} {ρ : Z ⟶ X}
    (hπ : I.IsBlowup π) (hρ : I.IsBlowup ρ) : ∃ e : Y ≅ Z, e.hom ≫ ρ = π := by
  obtain ⟨g, hg, _⟩ := hρ.universal Y π hπ.isEffectiveCartier
  obtain ⟨h, hh, _⟩ := hπ.universal Z ρ hρ.isEffectiveCartier
  refine ⟨⟨g, h, ?_, ?_⟩, hg⟩
  · exact hπ.hom_ext hπ.isEffectiveCartier (by simp [Category.assoc, hh, hg])
      (by simp)
  · exact hρ.hom_ext hρ.isEffectiveCartier (by simp [Category.assoc, hg, hh])
      (by simp)

/-- Any blowup in an effective Cartier ideal is an isomorphism. -/
theorem IsBlowup.isIso_of_isEffectiveCartier {I : X.IdealSheafData} {π : Y ⟶ X}
    (hπ : I.IsBlowup π) (hI : I.IsEffectiveCartier) : IsIso π := by
  obtain ⟨e, he⟩ := hπ.exists_iso hI.isBlowup_id
  have he' : e.hom = π := by simpa using he
  rw [← he']
  infer_instance

end IdealSheafData

/-- A finite sequence of blowups whose centers satisfy `P` over the fixed base `S`.
The identity is the sequence of length zero. -/
inductive BlowupSequence {S : Scheme.{u}}
    (P : ∀ X : Scheme.{u}, (X ⟶ S) → X.IdealSheafData → Prop) :
    {X Y : Scheme.{u}} → (X ⟶ S) → (Y ⟶ X) → Prop
  | nil {X : Scheme.{u}} (sX : X ⟶ S) : BlowupSequence P sX (𝟙 X)
  | cons {X Y Z : Scheme.{u}} {sX : X ⟶ S} {π : Y ⟶ X} {f : Z ⟶ Y}
      (I : X.IdealSheafData) (hπ : I.IsBlowup π) (hI : P X sX I)
      (tail : BlowupSequence P (π ≫ sX) f) : BlowupSequence P sX (f ≫ π)

/-- A condition on centers may be weakened throughout a blowup sequence. -/
theorem BlowupSequence.mono {S X Y : Scheme.{u}}
    {P Q : ∀ X : Scheme.{u}, (X ⟶ S) → X.IdealSheafData → Prop}
    (hPQ : ∀ (X : Scheme.{u}) (sX : X ⟶ S) (I : X.IdealSheafData),
      P X sX I → Q X sX I)
    {sX : X ⟶ S} {f : Y ⟶ X} (h : BlowupSequence P sX f) :
    BlowupSequence Q sX f := by
  induction h with
  | nil sX => exact .nil sX
  | cons I hπ hI _ ih => exact .cons I hπ (hPQ _ _ I hI) ih

end AlgebraicGeometry.Scheme
