/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesForMathlib.Definitions.AlgebraicGeometry.CycleClass

/-!
# The cycle class in codimension zero

Lemmas about the definitions in
`FormalConjecturesForMathlib.Definitions.AlgebraicGeometry.CycleClass`.
-/

@[expose] public noncomputable section

open CategoryTheory Order TopologicalSpace

namespace AlgebraicGeometry.ComplexPoint

open Point

variable (X : Over (Spec ↧ℂ))

/-- Evaluation of the integral codimension-zero class map on a represented cycle. -/
@[simp] lemma codimensionZeroChowCycleClass_mk
    [IsIntegral X.left] [Smooth X.hom]
    [IsProjective X.hom] (z : CodimensionCycle X.left 0) :
    codimensionZeroChowCycleClass X (ChowGroup.mk z) =
      codimensionZeroCycleClassOnCycles X z :=
  ChowGroup.liftCycleClass_mk _ _ _

/-- The generic component with coefficient one maps to the unit in degree-zero cohomology. -/
@[simp] lemma codimensionZeroCycleClass_genericPoint
    [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] :
    codimensionZeroCycleClass X
        (ChowGroup.toRational
          (ChowGroup.mk (CodimensionCycle.single (genericPoint X.left)
            (Order.IsMax.coheight_eq_zero isMax_top) 1))) =
      fieldCohomologyUnit ℚ X := by
  unfold codimensionZeroCycleClass
  rw [ChowGroup.toRational_apply, ChowGroup.rationalExtension_tmul, one_smul,
    codimensionZeroChowCycleClass_mk]
  let z : CodimensionCycle X.left 0 :=
    CodimensionCycle.single (genericPoint X.left)
      (Order.IsMax.coheight_eq_zero isMax_top) 1
  have hz : CodimensionCycle.integralEquiv z = 1 := by
    change z (genericPoint X.left) = 1
    dsimp [z]
    exact CodimensionCycle.single_same (p := 0) (genericPoint X.left) _ 1
  change fieldCohomologyClass ℚ X
      ((CodimensionCycle.integralEquiv z : ℤ) : ℚ) =
    fieldCohomologyClass ℚ X 1
  rw [hz]
  norm_num

/-- In codimension zero the actual cycle-class span is the line generated by the cohomological
unit. This statement does not assert that the unit spans all of `H⁰`; that further conclusion
requires connectedness of the analytic space. -/
lemma codimensionZeroCycleClassSpan_eq_span_unit
    [IsIntegral X.left] [Smooth X.hom] [IsProjective X.hom] :
    codimensionZeroCycleClassSpan X =
      Submodule.span ℚ {fieldCohomologyUnit ℚ X} := by
  apply le_antisymm
  · rintro α ⟨z, rfl⟩
    rw [ChowGroup.rational_eq_smul_genericPoint X.left z, map_smul,
      codimensionZeroCycleClass_genericPoint]
    exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton _))
  · exact Submodule.span_le.mpr (Set.singleton_subset_iff.mpr
      ⟨ChowGroup.toRational
        (ChowGroup.mk (CodimensionCycle.single (genericPoint X.left)
          (Order.IsMax.coheight_eq_zero isMax_top) 1)),
        codimensionZeroCycleClass_genericPoint X⟩)

end AlgebraicGeometry.ComplexPoint
