/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

open Nat Real

/--
A217317: Number of primes between $n^2$ and $n^2 + \log_2(n)^2$ (inclusive).
The sequence is generated by the formula $\pi(\lfloor n^2 + \log_2(n)^2 \rfloor) - \pi(n^2)$,
which counts primes strictly greater than $n^2$ (if $n > 1$).
-/
noncomputable def A217317 (n : ℕ) : ℕ :=
  if n = 0 then 0
  else
    -- Calculate the upper bound $\lfloor n^2 + \log_2(n)^2 \rfloor$
    -- Note: (Real.logb 2 n) is $\log_2(n)$.
    let upper_bound_real : ℝ := (n : ℝ)^2 + (Real.logb 2 n)^2
    let upper_bound_nat : ℕ := Int.toNat (Int.floor upper_bound_real)

    -- The formula $\pi(b) - \pi(a)$ counts primes $p$ such that $a < p \le b$.
    Nat.primeCounting upper_bound_nat - Nat.primeCounting (n^2)

/--
Conjecture: $a(n) > 0$ for $n > 4765516$.
This conjecture is consistent with Granville's conjecture that
$\limsup_{n \to \infty} \frac{p_{n+1}-p_n}{\log(p_n)^2} \ge \frac{2}{e^\gamma}$,
where $\gamma$ is Euler's constant.
-/
theorem oeis_A217317_conjecture : ∀ n : ℕ, n > 4765516 → A217317 n > 0 := by
  sorry
