/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

open Nat Finset List

/--
A346064: Number of primes that may be generated by changing any two digits of $n$ simultaneously.
-/
noncomputable def A346064 (n : ℕ) : ℕ :=
  if n < 10 then 0 else
  let D := Nat.digits 10 n
  let L := D.length

  -- Set of all available indices {0, 1, ..., L-1}
  let indices := Finset.range L
  -- Set of all available replacement digits {0, 1, ..., 9}
  let all_digits := Finset.range 10

  -- Pairs of distinct indices (i, j) with i < j
  let index_pairs : Finset (ℕ × ℕ) :=
    (indices.product indices).filter (fun p => p.fst < p.snd)

  -- Finset of all transformed numbers
  let transformed_numbers : Finset ℕ := index_pairs.biUnion fun ⟨i, j⟩ =>
    -- Using list indexing D[i]! which is safe because i, j ∈ Finset.range L.
    let d_i_orig := D[i]!
    let d_j_orig := D[j]!

    -- Filter replacement digits: r ≠ d_i_orig and s ≠ d_j_orig
    let allowed_replacements_r := all_digits.filter (fun r => r ≠ d_i_orig)
    let allowed_replacements_s := all_digits.filter (fun s => s ≠ d_j_orig)

    -- Using explicit Finset.image application to avoid dot notation ambiguity
    Finset.image (fun ⟨r, s⟩ =>
      let D' := D.set i r
      let D'' := D'.set j s
      -- Nat.ofDigits correctly handles leading zeros since D is LSF (little-endian).
      Nat.ofDigits 10 D''
    ) (Finset.product allowed_replacements_r allowed_replacements_s)

  -- Count the number of primes in the generated set
  (transformed_numbers.filter Nat.Prime).card


theorem a_10 : A346064 10 = 21 := by
  delta A346064
  norm_num+decide [ Finset.filter_biUnion,List.set, Finset.filter_image]

theorem a_11 : A346064 11 = 17 := by
  delta A346064
  norm_num+decide [ Finset.filter_biUnion,List.set, Finset.filter_image]

theorem a_12 : A346064 12 = 20 := by
  (inhabit Int)
  delta A346064
  norm_num+decide[ Finset.filter_biUnion]

theorem a_13 : A346064 13 = 15 := by
  nontriviality
  rw[A346064]
  norm_num+decide [ Finset.filter_biUnion,Finset.filter_image]


/-- By heuristic considerations it is conjectured that a(n) > 0 for all n >= 10. -/
theorem oeis_346064_conjecture_0 : ∀ n, 10 ≤ n → A346064 n > 0 := by
  sorry
