/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/


import FormalConjecturesUtil

/-!
# The Dichotomy Theorem for finite simple groups

The Dichotomy Theorem is one of the pillars of the classification of the finite simple groups.
It splits the simple groups into two families that are then treated by different methods: a
finite simple group whose $2$-subgroups are not all generated by four elements is either of
*component type* or of *characteristic $2$ type*. The groups excluded by that hypothesis, those
all of whose $2$-subgroups are generated by at most four elements, are classified by the
Gorenstein--Harada theorem.

Stating the dichotomy needs no enumeration of simple groups, because both alternatives are
intrinsic properties of $G$: being of component type is a condition on the centralizers of
involutions, and being of characteristic $2$ type is a condition on the $2$-local subgroups.

*References:*
* D. Gorenstein, K. Harada, *Finite groups whose 2-subgroups are generated by at most 4 elements*,
  Memoirs of the American Mathematical Society **147**, AMS (1974).
* D. Gorenstein, R. Lyons, R. Solomon, *The Classification of the Finite Simple Groups, Number 1*,
  Mathematical Surveys and Monographs **40.1**, AMS (1994), Chapter 2.
* D. Gorenstein, *Finite Simple Groups: An Introduction to Their Classification*, Plenum (1982),
  Chapter 4.
* [Classification of finite simple groups](https://en.wikipedia.org/wiki/Classification_of_finite_simple_groups)
-/

namespace Dichotomy

variable (G : Type*) [Group G]

/-- The join of the normal subgroups of `G` that satisfy `P`. -/
def core (P : Subgroup G → Prop) : Subgroup G :=
  ⨆ K : {K : Subgroup G // K.Normal ∧ P K}, K.1

instance core_normal (P : Subgroup G → Prop) : (core G P).Normal := by
  have : ∀ K : {K : Subgroup G // K.Normal ∧ P K}, (K.1).Normal := fun K => K.2.1
  exact Subgroup.iSup_normal _

/-- $O_p(G)$, the join of the normal $p$-subgroups of `G`. For a finite group this is the
largest normal $p$-subgroup. -/
def pCore (p : ℕ) : Subgroup G := core G fun K => IsPGroup p K

/-- $O(G)$, the join of the normal subgroups of `G` of odd order. For a finite group this is
the largest normal subgroup of odd order. -/
def oddCore : Subgroup G := core G fun K => Odd (Nat.card K)

instance pCore_normal (p : ℕ) : (pCore G p).Normal := core_normal _ _

instance oddCore_normal : (oddCore G).Normal := core_normal _ _

/-- A group is *quasisimple* if it is perfect and simple modulo its centre. -/
structure IsQuasisimple : Prop where
  /-- A quasisimple group is perfect. -/
  isPerfect : Group.IsPerfect G
  /-- A quasisimple group is simple modulo its centre. -/
  isSimpleGroup_quotient_center : IsSimpleGroup (G ⧸ Subgroup.center G)

/-- A *$2$-component* of `G` is a subnormal subgroup `K` such that $K / O(K)$ is quasisimple. -/
def IsTwoComponent (K : Subgroup G) : Prop :=
  K.IsSubnormal ∧ IsQuasisimple (K ⧸ oddCore K)

/-- `G` is of *component type* if the centralizer of some involution has a $2$-component. -/
def IsComponentType : Prop :=
  ∃ t : G, orderOf t = 2 ∧ ∃ K : Subgroup (Subgroup.centralizer {t}),
    IsTwoComponent (Subgroup.centralizer ({t} : Set G)) K

/-- A *$2$-local* subgroup of `G` is the normalizer of a nontrivial $2$-subgroup. -/
def IsTwoLocal (M : Subgroup G) : Prop :=
  ∃ P : Subgroup G, P ≠ ⊥ ∧ IsPGroup 2 P ∧ M = Subgroup.normalizer (P : Set G)

/-- `G` is of *characteristic $2$ type* if every $2$-local subgroup `M` of `G` satisfies
$C_M(O_2(M)) \le O_2(M)$. -/
def IsCharacteristicTwoType : Prop :=
  ∀ M : Subgroup G, IsTwoLocal G M →
    Subgroup.centralizer (pCore M 2 : Set M) ≤ pCore M 2

/-- Every $2$-subgroup of `G` can be generated by at most `k` elements. Equivalently, the
sectional $2$-rank of `G` is at most `k`. -/
def TwoSubgroupsGeneratedBy (k : ℕ) : Prop :=
  ∀ P : Subgroup G, IsPGroup 2 P → ∃ S : Finset P, S.card ≤ k ∧ Subgroup.closure (S : Set P) = ⊤

@[category API, AMS 20]
theorem TwoSubgroupsGeneratedBy.mono {k l : ℕ} (hkl : k ≤ l)
    (h : TwoSubgroupsGeneratedBy G k) : TwoSubgroupsGeneratedBy G l := by
  intro P hP
  obtain ⟨S, hcard, hgen⟩ := h P hP
  exact ⟨S, hcard.trans hkl, hgen⟩

@[category test, AMS 20]
theorem twoSubgroupsGeneratedBy_zero [Subsingleton G] : TwoSubgroupsGeneratedBy G 0 := by
  intro P _
  exact ⟨∅, le_rfl, Subsingleton.elim _ _⟩

/--
**The Dichotomy Theorem.** Let $G$ be a finite simple group in which some $2$-subgroup cannot be
generated by four elements. Then $G$ is of component type or of characteristic $2$ type.
-/
@[category research solved, AMS 20]
theorem isComponentType_or_isCharacteristicTwoType [Finite G] (hG : IsSimpleGroup G)
    (h : ¬TwoSubgroupsGeneratedBy G 4) :
    IsComponentType G ∨ IsCharacteristicTwoType G := by
  sorry

end Dichotomy
