/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Erdős Problem 1165

*References:*
- [erdosproblems.com/1165](https://www.erdosproblems.com/1165)
- [HLOZ24] C. Hao, X. Li, I. Okada, and Y. Zheng, [Favorite sites for simple random walk in two
  and more dimensions](https://arxiv.org/abs/2409.00995). arXiv:2409.00995 (2024).
- [To01] Tóth, Bálint, *No more than three favorite sites for simple random walk*. Ann. Probab.
  (2001), 484--503.
-/

open MeasureTheory Filter Set
open scoped Topology

namespace Erdos1165

/-- The four nearest-neighbour steps on $\mathbb{Z}^2$. -/
def dir : Fin 4 → ℤ × ℤ
  | 0 => (1, 0)
  | 1 => (-1, 0)
  | 2 => (0, 1)
  | 3 => (0, -1)

/-- Uniform probability on the four lattice directions. -/
noncomputable def dirMeasure : Measure (Fin 4) :=
  (PMF.uniformOfFintype (Fin 4)).toMeasure

/-- Law of i.i.d. simple-random-walk directions on $\mathbb{Z}^2$. -/
noncomputable def walkMeasure : Measure (ℕ → Fin 4) :=
  Measure.infinitePi fun _ : ℕ ↦ dirMeasure

/-- Simple random walk on $\mathbb{Z}^2$ generated by the steps `ω`, starting at the origin. -/
def walk (ω : ℕ → Fin 4) (n : ℕ) : ℤ × ℤ :=
  ∑ k ∈ Finset.range n, dir (ω k)

/-- $f_n(x)$: the number of visits to $x$ among times $0,\ldots,n$. -/
def localTime (ω : ℕ → Fin 4) (n : ℕ) (x : ℤ × ℤ) : ℕ :=
  ((Finset.range (n + 1)).filter fun l ↦ walk ω l = x).card

/-- $F(n)$: the set of favourite values at time $n$. -/
def favouriteValues (ω : ℕ → Fin 4) (n : ℕ) : Set (ℤ × ℤ) :=
  {x | ∀ y, localTime ω n y ≤ localTime ω n x}

/-- Each of the four directions has mass $1/4$. -/
@[category API, AMS 60]
theorem dirMeasure_apply (i : Fin 4) : dirMeasure {i} = 4⁻¹ := by
  unfold dirMeasure
  rw [PMF.toMeasure_apply_singleton _ i (MeasurableSet.singleton i)]
  simp [PMF.uniformOfFintype_apply]

/-- `dirMeasure` is a probability measure. -/
@[category API, AMS 60]
instance dirMeasure_isProbabilityMeasure : IsProbabilityMeasure dirMeasure :=
  inferInstanceAs (IsProbabilityMeasure (PMF.uniformOfFintype (Fin 4)).toMeasure)

/-- `walkMeasure` is a probability measure. -/
@[category API, AMS 60]
instance walkMeasure_isProbabilityMeasure : IsProbabilityMeasure walkMeasure := by
  dsimp [walkMeasure]
  infer_instance

/-- The walk starts at the origin. -/
@[category test, AMS 60]
theorem walk_zero (ω : ℕ → Fin 4) : walk ω 0 = 0 := by
  simp [walk]

/-- Each step has Euclidean length $1$. -/
@[category test, AMS 60]
theorem dir_sq (i : Fin 4) : (dir i).1 ^ 2 + (dir i).2 ^ 2 = 1 := by
  fin_cases i <;> simp [dir]

/-- At time $0$ the origin has been visited once. -/
@[category test, AMS 60]
theorem localTime_zero_origin (ω : ℕ → Fin 4) : localTime ω 0 0 = 1 := by
  simp [localTime, walk, Finset.filter_singleton]

/--
Given a random walk $s_0,s_1,\ldots$ in $\mathbb{Z}^2$, starting at the origin, let $f_n(x)$
count the number of $0\leq k\leq n$ such that $s_k=x$.

Let
$$
F(n)=\{ x: f_n(x) = \max_y f_n(y)\}
$$
be the set of 'favourite values'. Find
$$
\mathbb{P}(\lvert F(n)\rvert=r\textrm{ infinitely often})
$$
for $r\geq 3$.

A problem of Erdős and Révész.

Tóth [To01] proved that this probability is $0$ for all $r\geq 4$. Hao, Li, Okada, and Zheng
[HLOZ24] proved that this probability is $1$ for $r=3$.
-/
@[category research solved, AMS 60]
theorem erdos_1165 (r : ℕ) (_hr : 3 ≤ r) :
    walkMeasure {ω | ∃ᶠ n in atTop, (favouriteValues ω n).ncard = r} =
      answer((if r = 3 then 1 else 0 : ENNReal)) := by
  sorry

/--
Tóth [To01]: for every $r\geq 4$,
$$
\mathbb{P}(\lvert F(n)\rvert=r\textrm{ infinitely often})=0.
$$
-/
@[category research solved, AMS 60]
theorem erdos_1165.variants.toth (r : ℕ) (_hr : 4 ≤ r) :
    walkMeasure {ω | ∃ᶠ n in atTop, (favouriteValues ω n).ncard = r} = 0 := by
  sorry

/--
Hao, Li, Okada, and Zheng [HLOZ24]:
$$
\mathbb{P}(\lvert F(n)\rvert=3\textrm{ infinitely often})=1.
$$
-/
@[category research solved, AMS 60]
theorem erdos_1165.variants.hao_li_okada_zheng :
    walkMeasure {ω | ∃ᶠ n in atTop, (favouriteValues ω n).ncard = 3} = 1 := by
  sorry

end Erdos1165
