/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Erdős Problem 1166

*References:*
- [erdosproblems.com/1166](https://www.erdosproblems.com/1166)
- [ErTa60] Erdős, P. and Taylor, S. J., *Some problems concerning the structure of random walk
  paths*. Acta Math. Acad. Sci. Hungar. (1960), 137--162.
- [Va99] Various, *Some of Paul's favorite problems*. Booklet produced for the conference
  "Paul Erdős and his mathematics", Budapest, July 1999 (1999).
-/

open MeasureTheory Filter Set
open scoped Topology

namespace Erdos1166

/-- The four nearest-neighbour steps on $\mathbb{Z}^2$. -/
def dir : Fin 4 → ℤ × ℤ
  | 0 => (1, 0)
  | 1 => (-1, 0)
  | 2 => (0, 1)
  | 3 => (0, -1)

/-- Uniform probability on the four lattice directions. -/
noncomputable def dirMeasure : Measure (Fin 4) :=
  (PMF.uniformOfFintype (Fin 4)).toMeasure

/-- Law of i.i.d. simple-random-walk directions on $\mathbb{Z}^2$. -/
noncomputable def walkMeasure : Measure (ℕ → Fin 4) :=
  Measure.infinitePi fun _ : ℕ ↦ dirMeasure

/-- Simple random walk on $\mathbb{Z}^2$ generated by the steps `ω`, starting at the origin. -/
def walk (ω : ℕ → Fin 4) (n : ℕ) : ℤ × ℤ :=
  ∑ k ∈ Finset.range n, dir (ω k)

/-- $f_k(x)$: the number of visits to $x$ among times $0,\ldots,k$. -/
def localTime (ω : ℕ → Fin 4) (k : ℕ) (x : ℤ × ℤ) : ℕ :=
  ((Finset.range (k + 1)).filter fun l ↦ walk ω l = x).card

/-- $F(k)$: the set of favourite values at time $k$. -/
def favouriteValues (ω : ℕ → Fin 4) (k : ℕ) : Set (ℤ × ℤ) :=
  {x | ∀ y, localTime ω k y ≤ localTime ω k x}

/-- Points that are favourite values at some time $k\le n$. -/
def favouriteValuesUpto (ω : ℕ → Fin 4) (n : ℕ) : Set (ℤ × ℤ) :=
  ⋃ k ∈ Finset.range (n + 1), favouriteValues ω k

/-- Each of the four directions has mass $1/4$. -/
@[category API, AMS 60]
theorem dirMeasure_apply (i : Fin 4) : dirMeasure {i} = 4⁻¹ := by
  unfold dirMeasure
  rw [PMF.toMeasure_apply_singleton _ i (MeasurableSet.singleton i)]
  simp [PMF.uniformOfFintype_apply]

/-- `dirMeasure` is a probability measure. -/
@[category API, AMS 60]
instance dirMeasure_isProbabilityMeasure : IsProbabilityMeasure dirMeasure :=
  inferInstanceAs (IsProbabilityMeasure (PMF.uniformOfFintype (Fin 4)).toMeasure)

/-- `walkMeasure` is a probability measure. -/
@[category API, AMS 60]
instance walkMeasure_isProbabilityMeasure : IsProbabilityMeasure walkMeasure := by
  dsimp [walkMeasure]
  infer_instance

/-- The walk starts at the origin. -/
@[category test, AMS 60]
theorem walk_zero (ω : ℕ → Fin 4) : walk ω 0 = 0 := by
  simp [walk]

/-- Each step has Euclidean length $1$. -/
@[category test, AMS 60]
theorem dir_sq (i : Fin 4) : (dir i).1 ^ 2 + (dir i).2 ^ 2 = 1 := by
  fin_cases i <;> simp [dir]

/-- At time $0$ the origin has been visited once. -/
@[category test, AMS 60]
theorem localTime_zero_origin (ω : ℕ → Fin 4) : localTime ω 0 0 = 1 := by
  simp [localTime, walk, Finset.filter_singleton]

/--
Given a random walk $s_0,s_1,\ldots$ in $\mathbb{Z}^2$, starting at the origin, let $f_k(x)$
count the number of $0\leq l\leq k$ such that $s_l=x$.

Let
$$
F(k)=\{ x: f_k(x) = \max_y f_k(y)\}
$$
be the set of 'favourite values'. Is it true that
$$
\left\lvert \bigcup_{k\leq n}F(k)\right\rvert \leq (\log n)^{O(1)}
$$
almost surely, for all but finitely many $n$?

A problem of Erdős and Révész. This is true: almost surely
$$
\left\lvert \bigcup_{k\leq n}F(k)\right\rvert \ll (\log n)^{2},
$$
which follows from the fact that almost surely $\lvert F(n)\rvert \leq 3$ for all large $n$
(see [1165](https://www.erdosproblems.com/1165)) and the result of Erdős and Taylor [ErTa60]
that, if $T_n$ is the maximum number of visits of a random walk by time $n$ to any fixed
point, then $T_n \ll (\log n)^2$.
-/
@[category research solved, AMS 60]
theorem erdos_1166 : answer(True) ↔
    ∃ C > (0 : ℝ),
      ∀ᵐ ω ∂walkMeasure,
        ∀ᶠ n in atTop,
          ((favouriteValuesUpto ω n).ncard : ℝ) ≤ (Real.log n) ^ C := by
  sorry

/--
Almost surely
$$
\left\lvert \bigcup_{k\leq n}F(k)\right\rvert \ll (\log n)^{2}.
$$
-/
@[category research solved, AMS 60]
theorem erdos_1166.variants.log_sq :
    ∃ C > (0 : ℝ),
      ∀ᵐ ω ∂walkMeasure,
        ∀ᶠ n in atTop,
          ((favouriteValuesUpto ω n).ncard : ℝ) ≤ C * (Real.log n) ^ (2 : ℝ) := by
  sorry

end Erdos1166
