/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 330: Minimal Bases with Positive Density

*Reference:* [erdosproblems.com/330](https://www.erdosproblems.com/330)

**Conjecture (informal).**
If `A ⊆ ℕ` is a minimal (order-2) additive basis with positive density, then for every `n ∈ A`
the set of integers **not** representable as a sum of two elements of `A \ {n}` has **positive upper density**.
-/

open Function Set Filter

namespace Erdos330

/-- The order-2 representation set generated by `A`. -/
def repSet (A : Set ℕ) : Set ℕ :=
  {m | ∃ a ∈ A, ∃ b ∈ A, a + b = m}

/-- `A` is an (order-2) additive basis of `ℕ` if all sufficiently large integers lie in `repSet A`. -/
def IsBasis (A : Set ℕ) : Prop :=
  (∀ᶠ m in atTop, m ∈ repSet A)

/-- `A` is a **minimal** (order-2) basis if removing any `n ∈ A` destroys the basis property. -/
def IsMinimalBasis (A : Set ℕ) : Prop :=
  IsBasis A ∧ ∀ ⦃n⦄, n ∈ A → ¬ IsBasis (A \ {n})

/-- Integers **not** representable from `A` when `n` is forbidden (i.e. using only `A \ {n}`). -/
def notRepWithout (A : Set ℕ) (n : ℕ) : Set ℕ :=
  {m | m ∉ repSet (A \ {n})}

/-! ## Main problem statement -/

/--
**Erdős Problem 330.**
Suppose `A ⊆ ℕ` is a minimal (order-2) basis with positive density.
Is it true that, for any `n ∈ A`, the (upper) density of integers which cannot be represented
without using `n` is positive?
-/
@[category research open, AMS 5 11]
theorem erdos_330 :
    ∀ (A : Set ℕ),
      IsMinimalBasis A →
      0 < upperDensity A →
      ∀ ⦃n : ℕ⦄, n ∈ A → 0 < upperDensity (notRepWithout A n) := by
  sorry

/-! ## Equivalent/auxiliary formulations (placeholders) -/

/-- Reformulation via complements of representation sets. -/
@[category research open, AMS 5 11]
theorem erdos_330.reformulation :
    (∀ (A : Set ℕ), IsMinimalBasis A → 0 < upperDensity A →
      ∀ ⦃n : ℕ⦄, n ∈ A → 0 < upperDensity (notRepWithout A n)) ↔
    (∀ (A : Set ℕ), IsMinimalBasis A → 0 < upperDensity A →
      ∀ ⦃n : ℕ⦄, n ∈ A → 0 < upperDensity {m | m ∉ repSet (A \ {n})}) := by
  sorry

/-- If the conclusion failed for some `n ∈ A`, one would get an `atTop`-large set of exceptional
integers that are representable without `n`; this would contradict minimality (sketch placeholder). -/
@[category research open, AMS 5 11]
theorem erdos_330.minimality_pressure :
    ∀ (A : Set ℕ), IsMinimalBasis A →
      (∃ ⦃n : ℕ⦄, n ∈ A ∧ upperDensity (notRepWithout A n) = 0) →
      False := by
  sorry

/-! ## Examples / sanity checks (order-2 basis API) -/

/-- If `A` is finite then `A` is not an order-2 basis (sanity check). -/
@[category undergraduate, AMS 5 11]
theorem finite_not_basis {A : Set ℕ} (hfin : A.Finite) : ¬ IsBasis A := by
  sorry

/-- Monotonicity of representation sets with respect to inclusion. -/
@[category undergraduate, AMS 5 11]
theorem repSet_mono {A B : Set ℕ} (hAB : A ⊆ B) : repSet A ⊆ repSet B := by
  intro m hm
  rcases hm with ⟨a, haA, b, hbA, hsum⟩
  exact ⟨a, hAB haA, b, hAB hbA, hsum⟩

/-- Removing an element cannot enlarge the representation set. -/
@[category undergraduate, AMS 5 11]
theorem repSet_diff_singleton_subset {A : Set ℕ} {n : ℕ} :
    repSet (A \ {n}) ⊆ repSet A := by
  exact repSet_mono (by intro x hx; exact And.left hx)

/-! ## Density helpers (placeholders tied to your ForMathlib `upperDensity`) -/

/-- If `S ⊆ T` and `upperDensity S = 0`, then `upperDensity T = 0` implies `upperDensity (T \ S) = 0`.
(Placeholder for a typical density subadditivity tool you may already have.) -/
@[category research open, AMS 5 11]
theorem upperDensity_diff_zero {S T : Set ℕ}
    (hST : S ⊆ T) (hS0 : upperDensity S = 0) (hT0 : upperDensity T = 0) :
    upperDensity (T \ S) = 0 := by
  sorry

/-- If `IsMinimalBasis A` and `0 < upperDensity A`, then for each `n ∈ A` the complement
of `repSet (A \ {n})` is not `upperDensity`-null. (Bridges minimality to the target inequality.) -/
@[category research open, AMS 5 11]
theorem minimality_implies_positive_exception_set
    {A : Set ℕ} (hmin : IsMinimalBasis A) (hpos : 0 < upperDensity A) :
    ∀ ⦃n : ℕ⦄, n ∈ A → upperDensity (notRepWithout A n) ≠ 0 := by
  sorry

end Erdos330
