/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 330: Minimal Bases with Positive Density

*Reference:* [erdosproblems.com/330](https://www.erdosproblems.com/330)

**Conjecture (informal).**
If `A ⊆ ℕ` is a minimal (order-2) additive basis with positive density, then for every `n ∈ A`
the set of integers **not** representable as a sum of two elements of `A \ {n}` has **positive upper density**.
-/

open Function Set Filter

namespace Erdos330

/-- The order-2 representation set generated by `A`. -/
def repSet (A : Set ℕ) : Set ℕ :=
  {m | ∃ a ∈ A, ∃ b ∈ A, a + b = m}

/-- `A` is an (order-2) additive basis of `ℕ` if all sufficiently large integers lie in `repSet A`. -/
def IsBasis (A : Set ℕ) : Prop :=
  (∀ᶠ m in atTop, m ∈ repSet A)

/-- `A` is a **minimal** (order-2) basis if removing any `n ∈ A` destroys the basis property. -/
def IsMinimalBasis (A : Set ℕ) : Prop :=
  IsBasis A ∧ ∀ {n}, n ∈ A → ¬ IsBasis (A \ {n})

/-- Integers **not** representable from `A` when `n` is forbidden (i.e. using only `A \ {n}`). -/
def notRepWithout (A : Set ℕ) (n : ℕ) : Set ℕ :=
  {m | m ∉ repSet (A \ {n})}

/-! ## Main problem statement -/

/--
**Erdős Problem 330.**
Suppose `A ⊆ ℕ` is a minimal (order-2) basis with positive density.
Is it true that, for any `n ∈ A`, the (upper) density of integers which cannot be represented
without using `n` is positive?
-/
@[category research open, AMS 5 11]
theorem erdos_330 :
    ∀ (A : Set ℕ),
      IsMinimalBasis A →
      0 < upperDensity A →
      ∀ {n : ℕ}, n ∈ A → 0 < upperDensity (notRepWithout A n) := by
  sorry

/-- Reformulation via complements of representation sets. -/
@[category research open, AMS 5 11]
theorem erdos_330.reformulation :
    (∀ (A : Set ℕ), IsMinimalBasis A → 0 < upperDensity A →
      ∀ {n : ℕ}, n ∈ A → 0 < upperDensity (notRepWithout A n)) ↔
    (∀ (A : Set ℕ), IsMinimalBasis A → 0 < upperDensity A →
      ∀ {n : ℕ}, n ∈ A → 0 < upperDensity {m | m ∉ repSet (A \ {n})}) := by
  sorry

/-- If the conclusion failed for some `n ∈ A`, one would get an `atTop`-large set of exceptional
integers that are representable without `n`; this would contradict minimality (sketch placeholder). -/
@[category research open, AMS 5 11]
theorem erdos_330.minimality_pressure :
    ∀ (A : Set ℕ), IsMinimalBasis A →
      (∃ (n : ℕ), n ∈ A ∧ upperDensity (notRepWithout A n) = 0) →
      False := by
  sorry

/-! ## Examples / sanity checks -/

@[category undergraduate, AMS 5 11]
theorem finite_not_basis {A : Set ℕ} (hfin : A.Finite) : ¬ IsBasis A := by
  sorry

@[category undergraduate, AMS 5 11]
theorem repSet_mono {A B : Set ℕ} (hAB : A ⊆ B) : repSet A ⊆ repSet B := by
  intro m hm
  rcases hm with ⟨a, haA, b, hbA, hsum⟩
  exact ⟨a, hAB haA, b, hAB hbA, hsum⟩

@[category undergraduate, AMS 5 11]
theorem repSet_diff_singleton_subset {A : Set ℕ} {n : ℕ} :
    repSet (A \ {n}) ⊆ repSet A :=
  repSet_mono (by intro x hx; exact And.left hx)

end Erdos330
