/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesUtil

/-!
# Erdős Problem 411

*References:*
- [erdosproblems.com/411](https://www.erdosproblems.com/411)
- [ErGr80] Erdős, P. and Graham, R., _Old and new problems and results in
  combinatorial number theory_. Monographies de L'Enseignement Mathematique (1980), p. 81.
- [St25] Steinerberger, S., _On an iterated arithmetic function problem of Erdős and Graham_.
  [arXiv:2504.08023](https://arxiv.org/abs/2504.08023) (2025).
-/

@[expose] public section

namespace Erdos411

/-- The arithmetic map in the source. -/
def step (n : ℕ) : ℕ := n + n.totient

/-- Iteration including the zero-fold iterate; $\operatorname{orbit}(1,n)=g_1(n)$. -/
def orbit : ℕ → ℕ → ℕ
  | 0, n => n
  | k + 1, n => step (orbit k n)

/-- Exact eventual multiplier relation; the threshold may depend on $n,r,a$. -/
def EventuallyMultiplies (n r a : ℕ) : Prop :=
  0 < n ∧ 0 < r ∧ ∃ K : ℕ, ∀ k : ℕ, K ≤ k →
    orbit (k + r) n = a * orbit k n

/-- The question asks to classify this set, including transient starting values. -/
def SolutionPairs : Set (ℕ × ℕ) :=
  {nr | EventuallyMultiplies nr.1 nr.2 2}

/-- An immediate two-step doubling state, distinct from an eventual starting value. -/
def CycleState (n : ℕ) : Prop :=
  0 < n ∧ n.totient + (step n).totient = n

instance (n : ℕ) : Decidable (CycleState n) :=
  inferInstanceAs (Decidable (0 < n ∧ n.totient + (step n).totient = n))
/-- The known immediate cycle families, generated by the base states:
4,6,10,14,70,94 and all their nonnegative powers-of-two multiples. -/
def KnownCycleFamily (n : ℕ) : Prop :=
  ∃ b ∈ ({4, 6, 10, 14, 70, 94} : Finset ℕ),
    ∃ a : ℕ, n = 2 ^ a * b

/-- A possible exceptional branch in Steinerberger's reduction. -/
def ExceptionalCycleFamily (n : ℕ) : Prop :=
  ∃ l m : ℕ, 1 ≤ l ∧ (8 * m + 7).Prime ∧
    10 ^ 10 ≤ 8 * m + 7 ∧ (6 * m + 5).totient = 4 * m + 4 ∧
    (n = 2 ^ l * (8 * m + 7) ∨ n = 2 ^ l * (6 * m + 5))

@[simp, category API, AMS 11]
theorem orbit_zero (n : ℕ) : orbit 0 n = n := rfl

@[simp, category API, AMS 11]
theorem orbit_succ (k n : ℕ) : orbit (k + 1) n = step (orbit k n) := rfl

@[category API, AMS 11]
theorem orbit_add (a b n : ℕ) : orbit (a + b) n = orbit b (orbit a n) := by
  induction b with
  | zero => simp [orbit]
  | succ b ih => simp [orbit, ih]

@[category API, AMS 11]
theorem le_step (n : ℕ) : n ≤ step n := by
  unfold step
  omega

@[category API, AMS 11]
theorem le_orbit (k n : ℕ) : n ≤ orbit k n := by
  induction k with
  | zero => exact le_rfl
  | succ k ih => exact le_trans ih (le_step (orbit k n))

@[category API, AMS 11]
theorem step_two_mul {n : ℕ} (hn : Even n) : step (2 * n) = 2 * step n := by
  simp only [step, Nat.totient_two_mul_of_even hn]
  ring

@[category API, AMS 11]
theorem step_even {n : ℕ} (hn : Even n) (hlarge : 2 < n) : Even (step n) :=
  hn.add (Nat.totient_even hlarge)

@[category API, AMS 11]
theorem orbit_even {n : ℕ} (hn : Even n) (hlarge : 2 < n) (k : ℕ) :
    Even (orbit k n) := by
  induction k with
  | zero => exact hn
  | succ k ih =>
    exact step_even ih (lt_of_lt_of_le hlarge (le_orbit k n))

@[category API, AMS 11]
theorem orbit_two_mul {n : ℕ} (hn : Even n) (hlarge : 2 < n) (k : ℕ) :
    orbit k (2 * n) = 2 * orbit k n := by
  induction k with
  | zero => rfl
  | succ k ih =>
    rw [orbit_succ, ih, step_two_mul (orbit_even hn hlarge k), orbit_succ]

@[category API, AMS 11]
theorem cycle_state_iff {n : ℕ} :
    CycleState n ↔ 0 < n ∧ orbit 2 n = 2 * n := by
  simp only [CycleState, orbit, step]
  omega

@[category API, AMS 11]
theorem cycle_state_large {n : ℕ} (h : CycleState n) : 2 < n := by
  have hp := h.1
  by_contra hn
  rcases (show n = 1 ∨ n = 2 by omega) with rfl | rfl
  · exact (by decide : ¬ CycleState 1) h
  · exact (by decide : ¬ CycleState 2) h

@[category API, AMS 11]
theorem cycle_state_even {n : ℕ} (h : CycleState n) : Even n := by
  have hn := cycle_state_large h
  have hg : 2 < step n := lt_of_lt_of_le hn (le_step n)
  have he := (Nat.totient_even hn).add (Nat.totient_even hg)
  rwa [h.2] at he

/-- Shift one cannot eventually double a positive orbit. -/
@[category API, AMS 11]
theorem no_shift_one {n : ℕ} : ¬ EventuallyMultiplies n 1 2 := by
  rintro ⟨hn, _, K, hK⟩
  have hpos : 0 < orbit K n := lt_of_lt_of_le hn (le_orbit K n)
  have hphi : 0 < (orbit K n).totient := Nat.totient_pos.mpr hpos
  have hlarge : 1 < orbit (K + 1) n := by
    rw [orbit_succ]
    unfold step
    omega
  have hlt := Nat.totient_lt (orbit (K + 1) n) hlarge
  have heq := hK (K + 1) (by omega)
  rw [orbit_succ] at heq
  unfold step at heq
  omega

/-- One exact two-step equality propagates forever from a positive cycle state. -/
@[category API, AMS 11]
theorem cycle_state_doubles {n : ℕ} (h : CycleState n) (k : ℕ) :
    orbit (k + 2) n = 2 * orbit k n := by
  calc
    orbit (k + 2) n = orbit (2 + k) n := by congr 1; omega
    _ = orbit k (orbit 2 n) := orbit_add 2 k n
    _ = orbit k (2 * n) := by rw [(cycle_state_iff.mp h).2]
    _ = 2 * orbit k n := orbit_two_mul (cycle_state_even h) (cycle_state_large h) k

/-- Precise r=2 reduction: the starting value need only enter a cycle state. -/
@[category API, AMS 11]
theorem eventually_two_iff_hits_cycle {n : ℕ} :
    EventuallyMultiplies n 2 2 ↔ 0 < n ∧ ∃ K : ℕ, CycleState (orbit K n) := by
  constructor
  · rintro ⟨hn, _, K, hK⟩
    refine ⟨hn, K, cycle_state_iff.mpr ⟨lt_of_lt_of_le hn (le_orbit K n), ?_⟩⟩
    rw [← orbit_add K 2 n]
    exact hK K le_rfl
  · rintro ⟨hn, K, hK⟩
    refine ⟨hn, by omega, K, ?_⟩
    intro k hk
    obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hk
    calc
      orbit (K + d + 2) n = orbit (d + 2) (orbit K n) := by
        rw [Nat.add_assoc, orbit_add]
      _ = 2 * orbit d (orbit K n) := cycle_state_doubles hK d
      _ = 2 * orbit (K + d) n := by rw [orbit_add]

/-- Doubling an immediate cycle state preserves the totient equation. -/
@[category API, AMS 11]
theorem cycle_state_two_mul {n : ℕ} (h : CycleState n) : CycleState (2 * n) := by
  apply cycle_state_iff.mpr
  refine ⟨by have := h.1; omega, ?_⟩
  rw [orbit_two_mul (cycle_state_even h) (cycle_state_large h) 2,
    (cycle_state_iff.mp h).2]

/-- Every nonnegative powers-of-two multiple of a base cycle state is a cycle state. -/
@[category API, AMS 11]
theorem cycle_state_scale {n : ℕ} (h : CycleState n) (a : ℕ) :
    CycleState (2 ^ a * n) := by
  induction a with
  | zero => simpa using h
  | succ a ih =>
    have ht := cycle_state_two_mul ih
    simpa only [pow_succ, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm] using ht

@[category API, AMS 11]
theorem cycle_state_known_base {b : ℕ}
    (hb : b ∈ ({4, 6, 10, 14, 70, 94} : Finset ℕ)) : CycleState b := by
  simp only [Finset.mem_insert, Finset.mem_singleton] at hb
  rcases hb with rfl | rfl | rfl | rfl | rfl | rfl <;> decide

@[category API, AMS 11]
theorem known_family_cycle_state {n : ℕ} (h : KnownCycleFamily n) : CycleState n := by
  rcases h with ⟨b, hb, a, rfl⟩
  exact cycle_state_scale (cycle_state_known_base hb) a

@[category API, AMS 11]
theorem known_family_eventual {n : ℕ} (h : KnownCycleFamily n) :
    EventuallyMultiplies n 2 2 := by
  have hc := known_family_cycle_state h
  exact eventually_two_iff_hits_cycle.mpr ⟨hc.1, 0, hc⟩

@[category test, AMS 11]
theorem example_10 : EventuallyMultiplies 10 2 2 :=
  known_family_eventual ⟨10, by decide, 0, by norm_num⟩

@[category test, AMS 11]
theorem example_94 : EventuallyMultiplies 94 2 2 :=
  known_family_eventual ⟨94, by decide, 0, by norm_num⟩

/-- A transient start: $18\to24\to32$, followed by a two-step doubling cycle. -/
@[category test, AMS 11]
theorem example_18 : EventuallyMultiplies 18 2 2 := by
  apply eventually_two_iff_hits_cycle.mpr
  refine ⟨by omega, 2, ?_⟩
  have h32 : orbit 2 18 = 32 := by decide
  rw [h32]
  exact known_family_cycle_state ⟨4, by decide, 3, by norm_num⟩

@[category test, AMS 11]
theorem eighteen_not_immediate : ¬ CycleState 18 := by decide

/-- The stronger property of immediate doubling from every index fails for 18. -/
@[category test, AMS 11]
theorem eighteen_not_doubling_from_zero :
    ¬ (∀ k : ℕ, orbit (k + 2) 18 = 2 * orbit k 18) := by
  intro h
  have hbad : orbit 2 18 ≠ 2 * orbit 0 18 := by decide
  exact hbad (h 0)

/--
Let $g_1=g(n)=n+\phi(n)$ and $g_k(n)=g(g_{k-1}(n))$.
For which $n$ and $r$ is it true that $g_{k+r}(n)=2g_k(n)$ for all large $k$?

Both $n$ and $r$ are positive. Including the zero-fold iterate does not change
the eventual condition.
-/
@[category research open, AMS 11]
theorem erdos_411 : SolutionPairs = answer(sorry) := by
  sorry

/--
An orbit-entry variant of Cambie's proposed classification on erdosproblems.com/411: eventual doubling occurs
exactly for shift $r=2$ and starting values whose orbits enter one of the six known
cycle families. The initial value need not itself be a cycle state.
-/
@[category research open, AMS 11]
theorem erdos_411.variants.orbit_entry_classification : answer(sorry) ↔
    ∀ n r : ℕ, EventuallyMultiplies n r 2 ↔
      (0 < n ∧ r = 2 ∧ ∃ K : ℕ, KnownCycleFamily (orbit K n)) := by
  sorry

/--
Steinerberger [St25] has shown that if $\phi(n)+\phi(n+\phi(n))=n$ for positive $n$,
then either $n$ belongs to one of the six known cycle families, or
$n=2^\ell(8m+7)$ or $n=2^\ell(6m+5)$, where $\ell\geq1$,
$8m+7\geq10^{10}$ is prime and $\phi(6m+5)=4m+4$.
The known families use base states $4,6,10,14,70,94$, since $n=2$ is not a cycle state.
-/
@[category research solved, AMS 11]
theorem erdos_411.variants.steinerberger : ∀ n : ℕ, CycleState n →
    KnownCycleFamily n ∨ ExceptionalCycleFamily n := by
  sorry

/--
Steinerberger [St25] asks whether the known solutions $5,35,1295,1679615$ are the only
positive solutions of $\phi(n)=\frac{2}{3}(n+1)$.
-/
@[category research open, AMS 11]
theorem erdos_411.variants.totient_equation : answer(sorry) ↔
    ∀ n : ℕ, 0 < n →
      (3 * n.totient = 2 * (n + 1) ↔
        n ∈ ({5, 35, 1295, 1679615} : Finset ℕ)) := by
  sorry

end Erdos411
