/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 520

*Reference:* [erdosproblems.com/520](https://www.erdosproblems.com/520)
-/

open Classical MeasureTheory ProbabilityTheory Real Nat Set Filter

section Erdos520

variable {Ω : Type*} [MeasureSpace Ω] [IsProbabilityMeasure (ℙ : Measure Ω)]

/--
A sequence of random variables `X` indexed by primes is a "Rademacher system" if
they are independent and uniformly distributed on `{-1, 1}`.
-/
def IsRademacherSystem (X : ℕ → Ω → ℝ) : Prop :=
  -- 1. Independence of X_p for p prime.
  iIndepFun (fun (p : { p : ℕ // p.Prime }) ↦ X p) ℙ ∧
  -- 2. Uniform distribution on {-1, 1}
  ∀ p, p.Prime → (ℙ {ω | X p ω = 1} = 1 / 2 ∧ ℙ {ω | X p ω = -1} = 1 / 2)

/--
The random multiplicative function `f` generated by the Rademacher sequence `X`.
For square-free `n`, `f(n)` is the product of `X_p` for `p | n`.
For non-square-free `n`, `f(n) = 0`.
-/
noncomputable def randomMultiplicative (X : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) : ℝ :=
  if Squarefree n then
    ∏ p ∈ n.primeFactors, X p ω
  else
    0

/--
The partial sum of the random multiplicative function up to `N`.
-/
noncomputable def partialSum (X : ℕ → Ω → ℝ) (N : ℕ) (ω : Ω) : ℝ :=
  ∑ m ∈ Finset.range (N + 1), randomMultiplicative X m ω

/--
The normalization factor: `sqrt(N * log (log N))`.
-/
noncomputable def lilNorm (N : ℕ) : ℝ :=
  sqrt (N * log (log N))

/--
Does there exist a constant c > 0 such that almost surely the limsup
of the normalized partial sums is c?
-/
@[category research open, AMS 11 60]
theorem erdos_520 :
    (∃ c > 0, ∀ (X : ℕ → Ω → ℝ), IsRademacherSystem X →
      ∀ᵐ ω, limsup (fun N ↦ partialSum X N ω / lilNorm N) atTop = c)
    ↔ answer(sorry) := by
  sorry

end Erdos520
