/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesForMathlib.AlgebraicTopology.SingularBarycentricOuterFaces

/-!
This module is ported from Paul Lezeau's corresponding file in
`sphere-six-complex` pull request #49, under the Apache-2.0 license.

# The prism identity for barycentric subdivision

The composite of barycentric subdivision with the last-vertex map is expected to be chain
homotopic to the identity.  Since simplicial chains are freely generated by simplices, the
remaining content is one coherent prism chain on each standard simplex.  This file isolates that
exact acyclic-model identity and constructs its natural degreewise operators on every simplicial
set.
-/

@[expose] public section

noncomputable section

open CategoryTheory CategoryTheory.Limits PartialOrder Simplicial

namespace AlgebraicTopology.Singular

/-- The universal top-dimensional simplex of `Δ[n]`. -/
public noncomputable def standardSimplexTopSimplex (n : ℕ) :
    (Δ[n] : SSet.{0}).obj (Opposite.op (SimplexCategory.mk n)) :=
  SSet.stdSimplex.objEquiv.symm (𝟙 (SimplexCategory.mk n))

/-- On the universal simplex, subdivision followed by last vertex minus the identity. -/
public noncomputable def standardBarycentricLastVertexDiscrepancy (n : ℕ) :
    AddCommGrpCat.of ℤ ⟶
      ((Δ[n] : SSet.{0}).chainComplex (AddCommGrpCat.of ℤ)).X n :=
  barycentricSubdivisionSimplexChain (Δ[n] : SSet.{0}) n
      (standardSimplexTopSimplex n) ≫
        (subdivisionLastVertexChainMap (Δ[n] : SSet.{0})).f n -
    (Δ[n] : SSet.{0}).ιChainComplex (standardSimplexTopSimplex n)

@[simp]
public theorem yonedaEquiv_symm_apply_standardSimplexTopSimplex
    {X : SSet.{0}} (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk n))) :
    (SSet.yonedaEquiv.symm x).app _ (standardSimplexTopSimplex n) = x := by
  change X.map (𝟙 (Opposite.op (SimplexCategory.mk n))) x = x
  simp

/-- The discrepancy on an arbitrary simplex is the transport of the universal discrepancy. -/
public theorem standardBarycentricLastVertexDiscrepancy_transport
    (X : SSet.{0}) (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk n))) :
    standardBarycentricLastVertexDiscrepancy n ≫
        (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
          (AddCommGrpCat.of ℤ)).f n =
      barycentricSubdivisionSimplexChain X n x ≫
          (subdivisionLastVertexChainMap X).f n -
        X.ιChainComplex x := by
  rw [standardBarycentricLastVertexDiscrepancy, Preadditive.sub_comp, Category.assoc]
  have hlast := congrArg (fun k ↦ k.f n)
    (subdivisionLastVertexChainMap_naturality (SSet.yonedaEquiv.symm x))
  change (SSet.chainComplexMap (SSet.sd.map (SSet.yonedaEquiv.symm x))
      (AddCommGrpCat.of ℤ)).f n ≫ (subdivisionLastVertexChainMap X).f n =
    (subdivisionLastVertexChainMap (Δ[n] : SSet.{0})).f n ≫
      (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
        (AddCommGrpCat.of ℤ)).f n at hlast
  rw [← hlast, ← Category.assoc, ← barycentricSubdivisionSimplexChain_naturality,
    SSet.ι_chainComplexMap_f]
  change barycentricSubdivisionSimplexChain X n
        ((SSet.yonedaEquiv.symm x).app _ (standardSimplexTopSimplex n)) ≫
      (subdivisionLastVertexChainMap X).f n -
        X.ιChainComplex
          ((SSet.yonedaEquiv.symm x).app _ (standardSimplexTopSimplex n)) = _
  rw [yonedaEquiv_symm_apply_standardSimplexTopSimplex]

/-- The face contribution made by lower-dimensional prism chains. -/
public noncomputable def standardPrismFaceChain
    (prism : ∀ n : ℕ, AddCommGrpCat.of ℤ ⟶
      ((Δ[n] : SSet.{0}).chainComplex (AddCommGrpCat.of ℤ)).X (n + 1))
    (m : ℕ) :
    AddCommGrpCat.of ℤ ⟶
      ((Δ[m] : SSet.{0}).chainComplex (AddCommGrpCat.of ℤ)).X m :=
  match m with
  | 0 => 0
  | n + 1 =>
      ∑ i : Fin (n + 2), (-1 : ℤ) ^ i.val •
        (prism n ≫
          (SSet.chainComplexMap
            (SSet.stdSimplex.map (SimplexCategory.δ i))
            (AddCommGrpCat.of ℤ)).f (n + 1))

/-- The smallest remaining acyclic-model datum.  Its equation is the literal universal-simplex
prism identity: discrepancy equals the prism boundary plus the transported prisms of all faces. -/
public structure BarycentricLastVertexPrismData where
  /-- The universal degree-raising prism chain on each standard simplex. -/
  prism : ∀ n : ℕ, AddCommGrpCat.of ℤ ⟶
    ((Δ[n] : SSet.{0}).chainComplex (AddCommGrpCat.of ℤ)).X (n + 1)
  /-- Its boundary is the subdivision-last-vertex discrepancy minus the transported face prisms. -/
  boundary : ∀ n : ℕ,
    standardBarycentricLastVertexDiscrepancy n =
      prism n ≫
          ((Δ[n] : SSet.{0}).chainComplex
            (AddCommGrpCat.of ℤ)).d (n + 1) n +
        standardPrismFaceChain prism n

/-- Transport a universal prism chain along the simplex represented by `x`. -/
public noncomputable def barycentricLastVertexPrismSimplexChain
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk n))) :
    AddCommGrpCat.of ℤ ⟶
      (X.chainComplex (AddCommGrpCat.of ℤ)).X (n + 1) :=
  P.prism n ≫
    (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
      (AddCommGrpCat.of ℤ)).f (n + 1)

/-- The degree-raising prism operator on the free integral simplicial chains of `X`. -/
public noncomputable def barycentricLastVertexPrismComponent
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ) :
    (X.chainComplex (AddCommGrpCat.of ℤ)).X n ⟶
      (X.chainComplex (AddCommGrpCat.of ℤ)).X (n + 1) :=
  Sigma.desc (barycentricLastVertexPrismSimplexChain P X n)

@[reassoc (attr := simp)]
public theorem iota_barycentricLastVertexPrismComponent
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk n))) :
    X.ιChainComplex x ≫ barycentricLastVertexPrismComponent P X n =
      barycentricLastVertexPrismSimplexChain P X n x := by
  apply Sigma.ι_desc

/-- The prism components are natural in the ambient simplicial set. -/
public theorem barycentricLastVertexPrismComponent_naturality
    (P : BarycentricLastVertexPrismData) {X Y : SSet.{0}}
    (f : X ⟶ Y) (n : ℕ) :
    (SSet.chainComplexMap f (AddCommGrpCat.of ℤ)).f n ≫
        barycentricLastVertexPrismComponent P Y n =
      barycentricLastVertexPrismComponent P X n ≫
        (SSet.chainComplexMap f (AddCommGrpCat.of ℤ)).f (n + 1) := by
  apply X.chainComplex_hom_ext
  intro x
  rw [← Category.assoc, SSet.ι_chainComplexMap_f, iota_barycentricLastVertexPrismComponent,
    ← Category.assoc, iota_barycentricLastVertexPrismComponent]
  unfold barycentricLastVertexPrismSimplexChain
  rw [← SSet.yonedaEquiv_symm_comp, Category.assoc]
  congr 1
  let F := (SSet.chainComplexFunctor AddCommGrpCat).obj (AddCommGrpCat.of ℤ)
  have hmap := F.map_comp (SSet.yonedaEquiv.symm x) f
  exact congrArg (fun k ↦ k.f (n + 1)) hmap

/-- Transporting the universal face-prism sum is the source differential followed by the
lower-dimensional prism component. -/
public theorem standardPrismFaceChain_transport_succ
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk (n + 1)))) :
    standardPrismFaceChain P.prism (n + 1) ≫
        (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
          (AddCommGrpCat.of ℤ)).f (n + 1) =
      X.ιChainComplex x ≫
        (X.chainComplex (AddCommGrpCat.of ℤ)).d (n + 1) n ≫
          barycentricLastVertexPrismComponent P X n := by
  rw [standardPrismFaceChain, Preadditive.sum_comp]
  simp only [Preadditive.zsmul_comp, Category.assoc]
  rw [← Category.assoc, SSet.ιChainComplex_d, Preadditive.sum_comp]
  simp only [Preadditive.zsmul_comp, iota_barycentricLastVertexPrismComponent,
    barycentricLastVertexPrismSimplexChain]
  apply Finset.sum_congr rfl
  intro i hi
  apply congrArg (fun k ↦ ((-1 : ℤ) ^ i.val) • k)
  let F := (SSet.chainComplexFunctor AddCommGrpCat).obj (AddCommGrpCat.of ℤ)
  have hδ := SSet.stdSimplex.δ_comp_yonedaEquiv_symm x i
  have hmap := F.congr_map hδ
  rw [Functor.map_comp] at hmap
  have hn := congrArg (fun k ↦ k.f (n + 1)) hmap
  change (SSet.chainComplexMap
        (SSet.stdSimplex.map (SimplexCategory.δ i))
        (AddCommGrpCat.of ℤ)).f (n + 1) ≫
      (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
        (AddCommGrpCat.of ℤ)).f (n + 1) =
    (SSet.chainComplexMap
      (SSet.yonedaEquiv.symm (X.δ i x))
      (AddCommGrpCat.of ℤ)).f (n + 1) at hn
  calc
    _ = P.prism n ≫
        ((SSet.chainComplexMap
            (SSet.stdSimplex.map (SimplexCategory.δ i))
            (AddCommGrpCat.of ℤ)).f (n + 1) ≫
          (SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
            (AddCommGrpCat.of ℤ)).f (n + 1)) := Category.assoc _ _ _
    _ = _ := congrArg (fun k ↦ P.prism n ≫ k) hn

/-- The universal prism equation transported to a positive-dimensional simplex. -/
public theorem barycentricLastVertexPrismSimplex_boundary_succ
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ)
    (x : X.obj (Opposite.op (SimplexCategory.mk (n + 1)))) :
    barycentricSubdivisionSimplexChain X (n + 1) x ≫
          (subdivisionLastVertexChainMap X).f (n + 1) -
        X.ιChainComplex x =
      barycentricLastVertexPrismSimplexChain P X (n + 1) x ≫
          (X.chainComplex (AddCommGrpCat.of ℤ)).d (n + 2) (n + 1) +
        X.ιChainComplex x ≫
          (X.chainComplex (AddCommGrpCat.of ℤ)).d (n + 1) n ≫
            barycentricLastVertexPrismComponent P X n := by
  rw [← standardBarycentricLastVertexDiscrepancy_transport, P.boundary, Preadditive.add_comp]
  apply congrArg₂ (· + ·)
  · unfold barycentricLastVertexPrismSimplexChain
    rw [Category.assoc, Category.assoc]
    congr 1
    exact ((SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
      (AddCommGrpCat.of ℤ)).comm (n + 2) (n + 1)).symm
  · exact standardPrismFaceChain_transport_succ P X n x

/-- The degree-zero universal prism equation has no lower-dimensional face term. -/
public theorem barycentricLastVertexPrismSimplex_boundary_zero
    (P : BarycentricLastVertexPrismData) (X : SSet.{0})
    (x : X.obj (Opposite.op (SimplexCategory.mk 0))) :
    barycentricSubdivisionSimplexChain X 0 x ≫
          (subdivisionLastVertexChainMap X).f 0 -
        X.ιChainComplex x =
      barycentricLastVertexPrismSimplexChain P X 0 x ≫
        (X.chainComplex (AddCommGrpCat.of ℤ)).d 1 0 := by
  rw [← standardBarycentricLastVertexDiscrepancy_transport, P.boundary, standardPrismFaceChain,
    add_zero]
  unfold barycentricLastVertexPrismSimplexChain
  rw [Category.assoc, Category.assoc]
  congr 1
  exact ((SSet.chainComplexMap (SSet.yonedaEquiv.symm x)
    (AddCommGrpCat.of ℤ)).comm 1 0).symm

/-- The transported prism operators satisfy the chain-homotopy equation in positive degrees. -/
public theorem barycentricLastVertexPrismComponent_identity_succ
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (n : ℕ) :
    (barycentricSubdivisionChainMapCanonical X ≫
          subdivisionLastVertexChainMap X).f (n + 1) =
      (X.chainComplex (AddCommGrpCat.of ℤ)).d (n + 1) n ≫
          barycentricLastVertexPrismComponent P X n +
        barycentricLastVertexPrismComponent P X (n + 1) ≫
          (X.chainComplex (AddCommGrpCat.of ℤ)).d (n + 2) (n + 1) +
        𝟙 ((X.chainComplex (AddCommGrpCat.of ℤ)).X (n + 1)) := by
  apply X.chainComplex_hom_ext
  intro x
  change X.ιChainComplex x ≫
      (barycentricSubdivisionComponent X (n + 1) ≫
        (subdivisionLastVertexChainMap X).f (n + 1)) = _
  rw [← Category.assoc, iota_barycentricSubdivisionComponent]
  simp only [Preadditive.comp_add, Category.comp_id]
  simp only [← Category.assoc, iota_barycentricLastVertexPrismComponent]
  rw [← sub_eq_iff_eq_add]
  simpa only [Category.assoc, add_comm] using
    barycentricLastVertexPrismSimplex_boundary_succ P X n x

/-- The transported prism operator satisfies the chain-homotopy equation in degree zero. -/
public theorem barycentricLastVertexPrismComponent_identity_zero
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) :
    (barycentricSubdivisionChainMapCanonical X ≫
          subdivisionLastVertexChainMap X).f 0 =
      barycentricLastVertexPrismComponent P X 0 ≫
          (X.chainComplex (AddCommGrpCat.of ℤ)).d 1 0 +
        𝟙 ((X.chainComplex (AddCommGrpCat.of ℤ)).X 0) := by
  apply X.chainComplex_hom_ext
  intro x
  change X.ιChainComplex x ≫
      (barycentricSubdivisionComponent X 0 ≫
        (subdivisionLastVertexChainMap X).f 0) = _
  rw [← Category.assoc, iota_barycentricSubdivisionComponent]
  simp only [Preadditive.comp_add, Category.comp_id]
  simp only [← Category.assoc, iota_barycentricLastVertexPrismComponent]
  rw [← sub_eq_iff_eq_add]
  exact barycentricLastVertexPrismSimplex_boundary_zero P X x

/-- The homotopy family, supported exactly from degree `i` to degree `i+1`. -/
public noncomputable def barycentricLastVertexPrismHom
    (P : BarycentricLastVertexPrismData) (X : SSet.{0})
    (i j : ℕ) :
    (X.chainComplex (AddCommGrpCat.of ℤ)).X i ⟶
      (X.chainComplex (AddCommGrpCat.of ℤ)).X j :=
  if h : j = i + 1 then by
    subst j
    exact barycentricLastVertexPrismComponent P X i
  else 0

@[simp]
public theorem barycentricLastVertexPrismHom_succ
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) (i : ℕ) :
    barycentricLastVertexPrismHom P X i (i + 1) =
      barycentricLastVertexPrismComponent P X i := by
  simp [barycentricLastVertexPrismHom]

/-- A coherent family of universal simplex prisms produces the desired chain homotopy. -/
public noncomputable def barycentricSubdivisionLastVertexHomotopy
    (P : BarycentricLastVertexPrismData) (X : SSet.{0}) :
    Homotopy
      (barycentricSubdivisionChainMapCanonical X ≫
        subdivisionLastVertexChainMap X)
      (𝟙 (X.chainComplex (AddCommGrpCat.of ℤ))) where
  hom := barycentricLastVertexPrismHom P X
  zero i j hij := by
    rw [barycentricLastVertexPrismHom]
    split_ifs with h
    · exfalso
      apply hij
      rw [ComplexShape.down_Rel]
      exact h.symm
    · rfl
  comm i := by
    cases i with
    | zero =>
        rw [Homotopy.dNext_zero_chainComplex,
          Homotopy.prevD_chainComplex]
        simp only [barycentricLastVertexPrismHom_succ, zero_add,
          HomologicalComplex.id_f]
        exact barycentricLastVertexPrismComponent_identity_zero P X
    | succ n =>
        rw [Homotopy.dNext_succ_chainComplex,
          Homotopy.prevD_chainComplex]
        simp only [barycentricLastVertexPrismHom_succ,
          HomologicalComplex.id_f]
        exact barycentricLastVertexPrismComponent_identity_succ P X n

end AlgebraicTopology.Singular
