/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Sawin: An explicit lower bound for the unit distance problem

*Reference:* [arxiv/2605.20579](https://arxiv.org/abs/2605.20579)
**An explicit lower bound for the unit distance problem**
by *Will Sawin* (2026).

Sawin gives the first explicit lower bound exponent for the disproof of Erdős's unit-distance
conjecture (see `FormalConjectures.ErdosProblems.«90»`): there exist arbitrarily large finite point
sets in `ℝ²` with at least `n^{1.014114} / C` unit-distance pairs. The proof factors through three
self-contained reductions, each posed below as its own benchmark challenge:

* `Sawin.lemma_2_lattice_to_unit_distances` — pure geometry of numbers; given a lattice in
  `ℝ^{2d}`, a projection to `ℝ²`, and a family of "matching" lattice vectors of bounded norm
  projecting to the unit circle, extract a planar point set with high unit-distance density.
* `Sawin.lemmas_11_12_tower` — existence of an infinite tower of totally real number fields with
  bounded root discriminant and prescribed split primes; this is where the Golod–Shafarevich
  inequality and the Hajir–Maire–Ramakrishna (2003) construction enter.
* `Sawin.theorem_1_explicit_lower_bound` — the main theorem assembled from the above.
-/

open Filter EuclideanGeometry NumberField
open scoped EuclideanGeometry

namespace Arxiv.«2605.20579»

/--
**Lemma 2 (Sawin, 2026).** *Lattice geometry of unit distances.*

Let `d ≥ 1`, `R ≥ 2`, and suppose `Λ ⊂ EuclideanSpace ℝ (Fin (2*d))` is a full-rank `ℤ`-lattice
equipped with an additive embedding `π : Λ →+ ℝ²`. Suppose `S ⊂ Λ` is a finite set of "matching"
vectors satisfying `‖v‖ ≤ 1` and `‖π v‖ = 1` for every `v ∈ S`, with `π` injective on the
`ℤ`-submodule generated by `S`. Then there exists a finite point set `U ⊂ ℝ²` such that

  `(unitDistancePairsCount U : ℝ) / (U.card : ℝ) ≥ (1 - 1/R)^(2*d) * S.card`.

Proved as Lemma 2 of [arXiv:2605.20579](https://arxiv.org/abs/2605.20579).
-/
@[category research solved, AMS 52]
theorem lemma_2_lattice_to_unit_distances
    (d : ℕ) (hd : 1 ≤ d) (R : ℝ) (hR : 2 ≤ R)
    (Λ : Submodule ℤ (EuclideanSpace ℝ (Fin (2*d))))
    (π : Λ →+ ℝ²) (hπ : Function.Injective π)
    (S : Finset Λ)
    (hS_norm : ∀ v ∈ S, ‖(v : EuclideanSpace ℝ (Fin (2*d)))‖ ≤ 1)
    (hS_proj : ∀ v ∈ S, ‖π v‖ = 1) :
    ∃ U : Finset ℝ², 0 < U.card ∧
      ((1 : ℝ) - 1/R) ^ (2*d) * (S.card : ℝ) * (U.card : ℝ) ≤
        (unitDistancePairsCount U : ℝ) := by
  sorry

/--
**Lemmas 11 & 12 (Sawin, 2026).** *Existence of a totally real tower with bounded root
discriminant and many split primes.*

There exist `rdBound : ℝ` and a *single* infinite set `Q` of rational primes such that for every
`N : ℕ` one can find a totally real number field `F / ℚ` of degree `≥ N` with absolute root
discriminant `|disc F|^{1/[F:ℚ]} ≤ rdBound` in which *every* prime `q ∈ Q` splits completely.

The crucial feature is the order of quantifiers: `Q` is fixed *before* `F`, so the same primes
must split completely in fields of *unbounded* degree. (Contrast: for any single fixed `F`,
Chebotarev already gives infinitely many completely split primes, so the per-field version
would be vacuous.) This uniform splitting in an unbounded tower is exactly what makes the
statement hard.

Proved as Lemmas 11–12 of [arXiv:2605.20579](https://arxiv.org/abs/2605.20579), via the
Golod–Shafarevich inequality for pro-2 groups together with the Hajir–Maire–Ramakrishna
(2003) tower construction. Both ingredients are currently absent from Mathlib, so the *formal*
verification of this statement remains a substantial sub-challenge.

Compare `Arxiv.«2605.20695».prop_2_3_totally_real_tower`, which refines this by requiring the
primes in `Q` to lie in the residue class `q ≡ 1 (mod 4)`.
-/
@[category research solved, AMS 11]
theorem lemmas_11_12_tower :
    ∃ (rdBound : ℝ) (Q : Set ℕ), Q.Infinite ∧ (∀ q ∈ Q, q.Prime) ∧
      ∀ N : ℕ, ∃ (F : Type) (_ : Field F) (_ : CharZero F) (_ : NumberField F)
        (_ : NumberField.IsTotallyReal F),
        N ≤ Module.finrank ℚ F ∧
        (|(NumberField.discr F : ℝ)|) ^ ((1 : ℝ) / Module.finrank ℚ F) ≤ rdBound ∧
        ∀ q ∈ Q, ∃ (factors : Finset (Ideal (𝓞 F))),
          factors.card = Module.finrank ℚ F ∧
          ∀ p ∈ factors, p.IsMaximal ∧ (q : 𝓞 F) ∈ p := by
  sorry

/--
**Theorem 1 (Sawin, 2026).** *Explicit lower bound for the unit-distance count.*

There is an absolute constant `C > 0` such that for arbitrarily large `n` there exists a finite
set `U ⊂ ℝ²` with `U.card = n` realising at least `n^{1.014114} / C` unit-distance pairs.

Proved as Theorem 1 of [arXiv:2605.20579](https://arxiv.org/abs/2605.20579). Together with
the constructive form recorded in `Erdos90.erdos_90.variants.sawin_explicit`, this is the
headline disproof of Erdős Problem 90.
-/
@[category research solved, AMS 52]
theorem theorem_1_explicit_lower_bound :
    ∃ C > (0 : ℝ),
      {n : ℕ | ∃ U : Finset ℝ², U.card = n ∧
        (n : ℝ) ^ ((1014114 : ℝ) / 1000000) ≤ C * (unitDistancePairsCount U : ℝ)}.Infinite := by
  sorry

end Arxiv.«2605.20579»
