/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Sawin: An explicit lower bound for the unit distance problem

*Reference:* [arxiv/2605.20579](https://arxiv.org/abs/2605.20579)
**An explicit lower bound for the unit distance problem**
by *Will Sawin* (2026).

Sawin gives the first explicit lower bound exponent for the disproof of Erdős's unit-distance
conjecture (see `FormalConjectures.ErdosProblems.«90»`): there exist arbitrarily large finite point
sets in `ℝ²` with at least `n^{1.014114} / C` unit-distance pairs. The proof factors through three
self-contained reductions, each posed below as its own benchmark challenge:

* `Sawin.lemma_2_lattice_to_unit_distances` — pure geometry of numbers; given a lattice in
  `ℝ^{2d}`, a projection to `ℝ²`, and a family of "matching" lattice vectors of bounded norm
  projecting to the unit circle, extract a planar point set with high unit-distance density.
* `Sawin.lemmas_11_12_tower` — existence of an infinite tower of totally real number fields with
  bounded root discriminant and prescribed split primes; this is where the Golod–Shafarevich
  inequality and the Hajir–Maire–Ramakrishna (2003) construction enter.
* `Sawin.theorem_1_explicit_lower_bound` — the main theorem assembled from the above.
-/

open Filter EuclideanGeometry
open scoped EuclideanGeometry

namespace Arxiv.«2605.20579»

/--
**Lemma 2 (Sawin, 2026).** *Lattice geometry of unit distances.*

Let `d ≥ 1`, `R ≥ 2`, and suppose `Λ ⊂ EuclideanSpace ℝ (Fin (2*d))` is a full-rank `ℤ`-lattice
equipped with an additive embedding `π : Λ →+ ℝ²`. Suppose `S ⊂ Λ` is a finite set of "matching"
vectors satisfying `‖v‖ ≤ 1` and `‖π v‖ = 1` for every `v ∈ S`, with `π` injective on the
`ℤ`-submodule generated by `S`. Then there exists a finite point set `U ⊂ ℝ²` such that

  `(unitDistancePairsCount U : ℝ) / (U.card : ℝ) ≥ (1 - 1/R)^(2*d) * S.card`.

Phrased here as a benchmark conjecture: such a `U` always exists.
-/
@[category research open, AMS 52]
theorem lemma_2_lattice_to_unit_distances
    (d : ℕ) (hd : 1 ≤ d) (R : ℝ) (hR : 2 ≤ R)
    (Λ : Submodule ℤ (EuclideanSpace ℝ (Fin (2*d))))
    (π : Λ →+ ℝ²) (hπ : Function.Injective π)
    (S : Finset Λ)
    (hS_norm : ∀ v ∈ S, ‖(v : EuclideanSpace ℝ (Fin (2*d)))‖ ≤ 1)
    (hS_proj : ∀ v ∈ S, ‖π v‖ = 1) :
    ∃ U : Finset ℝ², 0 < U.card ∧
      ((1 : ℝ) - 1/R) ^ (2*d) * (S.card : ℝ) * (U.card : ℝ) ≤
        (unitDistancePairsCount U : ℝ) := by
  sorry

/--
**Lemmas 11 & 12 (Sawin, 2026).** *Existence of a CM tower with prescribed split primes.*

There exist an infinite increasing sequence of degrees `(d_n)_{n}`, a constant `rdBound ≥ 1`, and for
each `n` a totally real number field `F_n` of degree `d_n` over `ℚ` and a CM quadratic extension
`K_n / F_n` such that:

* the relative root discriminant `rd(K_n / F_n)` is at most `rdBound`;
* infinitely many rational primes split completely in `K_n / ℚ`.

The proof in Sawin uses the Golod–Shafarevich inequality for pro-2 groups together with the
Hajir–Maire–Ramakrishna (2003) tower construction. Both ingredients are currently absent from
Mathlib, so this conjecture stands as a serious sub-challenge.
-/
@[category research open, AMS 11]
theorem lemmas_11_12_tower :
    ∃ (rdBound : ℝ) (_ : 1 ≤ rdBound),
      ∀ N : ℕ, ∃ (F : Type) (_ : Field F) (_ : NumberField F) (_ : Algebra ℚ F)
        (_ : NumberField.IsTotallyReal F)
        (K : Type) (_ : Field K) (_ : NumberField K) (_ : Algebra F K)
        (_ : NumberField.IsCMField K),
        N ≤ Module.finrank ℚ F := by
  sorry

/--
**Theorem 1 (Sawin, 2026).** *Explicit lower bound for the unit-distance count.*

There is an absolute constant `C > 0` such that for arbitrarily large `n` there exists a finite
set `U ⊂ ℝ²` with `U.card = n` realising at least `n^{1.014114} / C` unit-distance pairs.

Together with the constructive form recorded in
`Erdos90.erdos_90.variants.sawin_explicit`, this is the headline disproof of Erdős Problem 90.
-/
@[category research open, AMS 52]
theorem theorem_1_explicit_lower_bound :
    ∃ C > (0 : ℝ),
      {n : ℕ | ∃ U : Finset ℝ², U.card = n ∧
        (n : ℝ) ^ ((1014114 : ℝ) / 1000000) ≤ C * (unitDistancePairsCount U : ℝ)}.Infinite := by
  sorry

end Arxiv.«2605.20579»
