/-
Copyright 2026 The Formal Conjectures Authors..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Cunningham Chains — Jones's Conjecture

A *Cunningham chain of the first kind* is a sequence of primes
$p, 2p+1, 2(2p+1)+1, \ldots$ generated by the map $q \mapsto 2q+1$.
A *Cunningham chain of the second kind* uses the map $q \mapsto 2q-1$.

A chain has **exact length k** when its first $k$ terms are prime and the
$(k+1)$-th generated term is composite.

Lenny Jones conjectures that for every positive integer $k$, infinitely many
primes start a chain of exact length $k$, for each of the two kinds.

*Reference:* [arXiv:1104.1579](https://arxiv.org/abs/1104.1579)
-/

namespace Arxiv.«1104.1579»

/-- The `n`-th term of a first-kind Cunningham chain starting at `p`,
obtained by iterating `q ↦ 2q + 1`. -/
def cunninghamFirst (p : ℕ) : ℕ → ℕ
  | 0     => p
  | n + 1 => 2 * cunninghamFirst p n + 1

/-- The `n`-th term of a second-kind Cunningham chain starting at `p`,
obtained by iterating `q ↦ 2q - 1` (truncated subtraction on `ℕ`,
which is harmless since all terms in the intended domain are ≥ 2). -/
def cunninghamSecond (p : ℕ) : ℕ → ℕ
  | 0     => p
  | n + 1 => 2 * cunninghamSecond p n - 1

/-- `p` starts a first-kind Cunningham chain of **exact** length `k`:
the first `k` terms (indices `0` through `k-1`) are prime, and the
`k`-th generated term is composite. -/
def isExactFirstChain (k : ℕ) (p : ℕ) : Prop :=
  (∀ i < k, Nat.Prime (cunninghamFirst p i)) ∧
  ¬Nat.Prime (cunninghamFirst p k)

/-- `p` starts a second-kind Cunningham chain of **exact** length `k`:
the first `k` terms (indices `0` through `k-1`) are prime, and the
`k`-th generated term is composite. -/
def isExactSecondChain (k : ℕ) (p : ℕ) : Prop :=
  (∀ i < k, Nat.Prime (cunninghamSecond p i)) ∧
  ¬Nat.Prime (cunninghamSecond p k)

-- Sanity-check: 2 starts a first-kind chain of length ≥ 2
-- (2 is prime, 2·2+1 = 5 is prime, 2·5+1 = 11 is prime, 2·11+1 = 23 is prime,
--  2·23+1 = 47 is prime, 2·47+1 = 95 = 5·19 is composite).
@[category test, AMS 11]
theorem cunninghamFirst_example :
    cunninghamFirst 2 0 = 2 ∧
    cunninghamFirst 2 1 = 5 ∧
    cunninghamFirst 2 2 = 11 ∧
    cunninghamFirst 2 3 = 23 ∧
    cunninghamFirst 2 4 = 47 ∧
    cunninghamFirst 2 5 = 95 := by
  decide

-- Sanity-check: 19 starts a second-kind chain of length ≥ 2
-- (19 is prime, 2·19-1 = 37 is prime, 2·37-1 = 73 is prime,
--  2·73-1 = 145 = 5·29 is composite).
@[category test, AMS 11]
theorem cunninghamSecond_example :
    cunninghamSecond 19 0 = 19 ∧
    cunninghamSecond 19 1 = 37 ∧
    cunninghamSecond 19 2 = 73 ∧
    cunninghamSecond 19 3 = 145 := by
  decide

/--
Jones's conjecture (first kind): for every positive integer $k$, there are
infinitely many primes $p$ that start a first-kind Cunningham chain of
exactly length $k$.

That is, the set of primes starting an exact first-kind chain of length $k$
is infinite.
-/
@[category research open, AMS 11]
theorem infinitely_many_exact_first_chains (k : ℕ) (hk : 0 < k) :
    {p : ℕ | Nat.Prime p ∧ isExactFirstChain k p}.Infinite := by
  sorry

/--
Jones's conjecture (second kind): for every positive integer $k$, there are
infinitely many primes $p$ that start a second-kind Cunningham chain of
exactly length $k$.

That is, the set of primes starting an exact second-kind chain of length $k$
is infinite.
-/
@[category research open, AMS 11]
theorem infinitely_many_exact_second_chains (k : ℕ) (hk : 0 < k) :
    {p : ℕ | Nat.Prime p ∧ isExactSecondChain k p}.Infinite := by
  sorry

end Arxiv.«1104.1579»
