/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# The Gerstenhaber problem for three commuting matrices

Gerstenhaber proved in 1961 that the unital algebra generated by two commuting $n \times n$
matrices over a field has dimension at most $n$. It is an open problem, known as the
*Gerstenhaber problem*, whether the same bound holds for three pairwise commuting matrices.
The bound fails for four or more pairwise commuting matrices.

*Reference:* [arXiv:2402.16334](https://arxiv.org/abs/2402.16334), M. Satriano and
W. Zhang, "On the algebra generated by three commuting matrices: combinatorial cases"

*Reference:* [arXiv:2006.08588](https://arxiv.org/abs/2006.08588), J. Holbrook and
M. Omladič, "A computing strategy and programs to resolve the Gerstenhaber Problem for
commuting triples of matrices"
-/

namespace Gerstenhaber

variable {K : Type*} [Field K] {n : ℕ}

/--
**Gerstenhaber's theorem (1961).**
If $A$ and $B$ are commuting $n \times n$ matrices over a field $K$, then the unital
$K$-algebra $K[A, B]$ they generate has dimension at most $n$.
-/
@[category research solved, AMS 15 16]
theorem finrank_adjoin_pair_le (A B : Matrix (Fin n) (Fin n) K) (hAB : Commute A B) :
    Module.finrank K (Algebra.adjoin K {A, B}) ≤ n := by
  sorry

/--
**The Gerstenhaber problem.**
If $A$, $B$ and $C$ are pairwise commuting $n \times n$ matrices over a field $K$, is the
dimension of the unital $K$-algebra $K[A, B, C]$ they generate at most $n$?
-/
@[category research open, AMS 15 16]
theorem finrank_adjoin_triple_le (A B C : Matrix (Fin n) (Fin n) K) (hAB : Commute A B)
    (hAC : Commute A C) (hBC : Commute B C) :
    Module.finrank K (Algebra.adjoin K {A, B, C}) ≤ n := by
  sorry

/--
The analogue of Gerstenhaber's theorem fails for four pairwise commuting matrices: there are
$n$ and four pairwise commuting $n \times n$ matrices over $\mathbb{Q}$ generating a unital
algebra of dimension greater than $n$.
-/
@[category research solved, AMS 15 16]
theorem exists_finrank_adjoin_quadruple_gt :
    ∃ (n : ℕ) (A B C D : Matrix (Fin n) (Fin n) ℚ),
      (∀ M ∈ ({A, B, C, D} : Set (Matrix (Fin n) (Fin n) ℚ)),
        ∀ N ∈ ({A, B, C, D} : Set (Matrix (Fin n) (Fin n) ℚ)), Commute M N) ∧
      n < Module.finrank ℚ (Algebra.adjoin ℚ {A, B, C, D}) := by
  sorry

end Gerstenhaber
