/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Prime quadruplets generated by $p = 3\phi(k) + \phi(n-k) - 1$

Let $\phi$ denote Euler's totient function. The sequence $a(n)$ counts the number of integers
$0 < k < n$ such that $p = 3\phi(k) + \phi(n-k) - 1$, $p + 2$, $p + 6$, and $p + 8$ are all prime.

*References:*
- [A236511](https://oeis.org/A236511)
-/

namespace OeisA236511

/-- $a(n)$ is the number of integers $0 < k < n$ such that $p = 3\phi(k) + \phi(n-k) - 1$,
$p + 2$, $p + 6$, and $p + 8$ are all prime. -/
def a (n : ℕ) : ℕ :=
  ∑ k ∈ Finset.Ico 1 n,
    let p := 3 * k.totient + (n - k).totient - 1
    if p.Prime ∧ (p + 2).Prime ∧ (p + 6).Prime ∧ (p + 8).Prime then 1 else 0

/-- Value of the sequence `a` at 1. -/
@[category test, AMS 11]
theorem a_1 : a 1 = 0 := by decide

/-- Value of the sequence `a` at 2. -/
@[category test, AMS 11]
theorem a_2 : a 2 = 0 := by decide

/-- Value of the sequence `a` at 3. -/
@[category test, AMS 11]
theorem a_3 : a 3 = 0 := by decide

/-- Value of the sequence `a` at 4. -/
@[category test, AMS 11]
theorem a_4 : a 4 = 0 := by decide

/-- Value of the sequence `a` at 10. -/
@[category test, AMS 11]
theorem a_10 : a 10 = 1 := by decide

/--
Conjecture: $a(n) > 0$ for all $n > 1075$.
-/
@[category research open, AMS 11]
theorem conjecture (n : ℕ) (hn : 1075 < n) : 0 < a n := by
  sorry

end OeisA236511
