on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  # This re-runs the check every time a review is submitted
  pull_request_review:
    types: [submitted]
    branches:
      - main

permissions:
  contents: read

jobs:
  run-if-trusted-or-approved:
    runs-on: ubuntu-latest

    # This job ONLY runs if the PR author is trusted, OR a trusted
    # user has submitted an "approved" review.
    if: |
      ( contains(fromJSON(vars.TRUSTED_AUTHORS_JSON), github.event.pull_request.user.login) )
      ||
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved' &&
        contains(fromJSON(vars.TRUSTED_AUTHORS_JSON), github.event.review.user.login)
      )

    steps:
      - name: Condition Met
        run: |
          echo "This job is running because a valid condition was met."
          echo "Event Name: ${{ github.event_name }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"

          # This block is just for logging/debugging which condition passed
          if (contains(fromJSON(vars.TRUSTED_AUTHORS_JSON), github.event.pull_request.user.login)); then
            echo "Condition Path: The PR author is on the trusted list."
          else
            echo "Condition Path: A trusted reviewer (${{ github.event.review.user.login }}) approved the PR."
          fi
